/**
 * Reputation Shared Utilities.
 *
 * Purpose: Shared helpers for reputation commands.
 */
import type { GuildCommandContext } from "seyfert";

import {
  GUILD_ONLY_MESSAGE,
  requireGuildPermission,
} from "@/utils/commandGuards";
import { Features } from "@/modules/features";

export interface RepCommandContext {
  guildId: string;
}

export interface RepContextOptions {
  requirePermission?: boolean;
}

/**
 * Ensures the reputation system is enabled for the guild and optionally enforces
 * ManageGuild permission for moderation-only subcommands.
 */
export async function requireRepContext(
  ctx: GuildCommandContext,
  options: RepContextOptions = {},
): Promise<RepCommandContext | null> {
  if (!ctx.guildId) {
    await ctx.write({ content: GUILD_ONLY_MESSAGE });
    return null;
  }

  if (options.requirePermission ?? true) {
    const allowed = await requireGuildPermission(ctx, {
      guildId: ctx.guildId,
      permissions: ["ManageGuild"],
    });

    if (!allowed) {
      return null;
    }
  }

  const enabled = await import("@/modules/features").then((m) =>
    m.isFeatureEnabled(ctx.guildId!, Features.Reputation),
  );
  if (!enabled) {
    await ctx.write({
      content: "The reputation system is disabled on this server.",
      flags: 64, // MessageFlags.Ephemeral
    });
    return null;
  }

  return { guildId: ctx.guildId };
}

const MAX_DELTA = 1_000_000;

export function normalizeRepAmount(
  input: number | null | undefined,
): number | null {
  if (typeof input !== "number" || !Number.isFinite(input)) return null;
  const value = Math.trunc(input);
  if (value <= 0) return null;
  return Math.min(value, MAX_DELTA);
}

type RepChangeAction = "add" | "remove";

export function buildRepChangeMessage(
  action: RepChangeAction,
  amount: number,
  userId: string,
  total: number,
): string {
  const emoji = action === "add" ? "📈" : "📉";
  const verb = action === "add" ? "added" : "removed";
  return `${emoji} ${amount} reputation point(s) ${verb} for <@${userId}>. Current total: **${total}**.`;
}

import {
  ActionRow,
  Button,
  Embed,
  type TextGuildChannel,
  type Message,
  type User,
} from "seyfert";
import { ButtonStyle } from "seyfert/lib/types";
import { Colors } from "@/modules/ui/colors";

export async function sendReputationRequest(
  channel: TextGuildChannel,
  targetMessage: Message,
  requester: User,
  isAutoDetected: boolean = false,
) {
  const embed = new Embed()
    .setColor(Colors.info)
    .setTitle("Reputation Review Request")
    .setThumbnail(requester.avatarURL())
    .addFields([
      {
        name: "User",
        value: `<@${requester.id}> (${requester.username})`,
        inline: false,
      },
      {
        name: "Time",
        value: `<t:${Math.floor(Date.now() / 1000)}:f>`,
        inline: false,
      },
      { name: "Message", value: targetMessage.url },
    ]);

  if (isAutoDetected) {
    embed.setFooter({
      text: "This request was automatically generated by keyword detection.",
    });
  }

  const row1 = new ActionRow<Button>().addComponents(
    new Button()
      .setCustomId(`rep:accept:${requester.id}`)
      .setLabel("Accept (+1)")
      .setStyle(ButtonStyle.Success),
    new Button()
      .setCustomId(`rep:set:${requester.id}`)
      .setLabel("Manual Value")
      .setStyle(ButtonStyle.Primary),
    new Button()
      .setCustomId(`rep:deny:${requester.id}`)
      .setLabel("Deny (-1)")
      .setStyle(ButtonStyle.Danger),
  );

  const row2 = new ActionRow<Button>().addComponents(
    new Button()
      .setCustomId(`rep:close`)
      .setLabel("Close")
      .setStyle(ButtonStyle.Secondary),
    new Button()
      .setCustomId(`rep:penalize:${requester.id}`)
      .setLabel("Penalize")
      .setStyle(ButtonStyle.Danger),
  );

  await channel.messages.write({
    embeds: [embed],
    components: [row1, row2],
  });
}
