/**
 * General Knowledge Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const generalQuestions: TriviaQuestion[] = [
  // Difficulty 1
  {
    id: "general_001",
    question: "¿Cuál es el planeta más grande del sistema solar?",
    options: ["Tierra", "Saturno", "Júpiter", "Neptuno"],
    correctIndex: 2,
    category: "general",
    difficulty: 1,
    explanation: "Júpiter es el planeta más grande, con más de 300 veces la masa de la Tierra.",
    tags: ["space", "planets"],
  },
  {
    id: "general_002",
    question: "¿Cuántos continentes hay en la Tierra?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    category: "general",
    difficulty: 1,
    explanation: "Los 7 continentes son: África, Antártida, Asia, Europa, Norteamérica, Oceanía y Sudamérica.",
    tags: ["geography"],
  },
  {
    id: "general_003",
    question: "¿Qué gas respiran principalmente las plantas?",
    options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"],
    correctIndex: 1,
    category: "general",
    difficulty: 1,
    explanation: "Las plantas absorben CO2 y liberan oxígeno durante la fotosíntesis.",
    tags: ["biology", "nature"],
  },
  {
    id: "general_004",
    question: "¿Cuál es el océano más grande?",
    options: ["Atlántico", "Índico", "Pacífico", "Ártico"],
    correctIndex: 2,
    category: "general",
    difficulty: 1,
    explanation: "El Océano Pacífico cubre más del 30% de la superficie de la Tierra.",
    tags: ["geography", "ocean"],
  },
  {
    id: "general_005",
    question: "¿En qué país se encuentra la Torre Eiffel?",
    options: ["Reino Unido", "Italia", "Francia", "España"],
    correctIndex: 2,
    category: "general",
    difficulty: 1,
    explanation: "La Torre Eiffel está en París, Francia. Fue construida para la Exposición Universal de 1889.",
    tags: ["landmarks", "france"],
  },
  // Difficulty 2
  {
    id: "general_006",
    question: "¿En qué año llegó el hombre a la luna?",
    options: ["1965", "1969", "1972", "1959"],
    correctIndex: 1,
    category: "general",
    difficulty: 2,
    explanation: "Neil Armstrong pisó la Luna el 20 de julio de 1969 durante la misión Apollo 11.",
    tags: ["space", "history"],
  },
  {
    id: "general_007",
    question: "¿Cuál es el río más largo del mundo?",
    options: ["Nilo", "Amazonas", "Yangtsé", "Misisipi"],
    correctIndex: 1,
    category: "general",
    difficulty: 2,
    explanation: "El Amazonas es el río más largo (y más caudaloso) del mundo.",
    tags: ["geography", "rivers"],
  },
  {
    id: "general_008",
    question: "¿Quién pintó la Mona Lisa?",
    options: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Donatello"],
    correctIndex: 1,
    category: "general",
    difficulty: 2,
    explanation: "Leonardo da Vinci pintó la Mona Lisa (La Gioconda) entre 1503 y 1519.",
    tags: ["art", "history"],
  },
  {
    id: "general_009",
    question: "¿Cuál es el idioma más hablado del mundo?",
    options: ["Inglés", "Español", "Chino mandarín", "Hindi"],
    correctIndex: 2,
    category: "general",
    difficulty: 2,
    explanation: "El chino mandarín tiene más hablantes nativos, aunque el inglés es más extendido globalmente.",
    tags: ["language", "culture"],
  },
  {
    id: "general_010",
    question: "¿Qué país inventó el papel?",
    options: ["Egipto", "China", "Grecia", "Roma"],
    correctIndex: 1,
    category: "general",
    difficulty: 2,
    explanation: "China inventó el papel durante la dinastía Han, alrededor del año 105 d.C.",
    tags: ["history", "inventions"],
  },
  // Difficulty 3
  {
    id: "general_011",
    question: "¿Cuál es la montaña más alta del mundo?",
    options: ["K2", "Monte Everest", "Kilimanjaro", "Aconcagua"],
    correctIndex: 1,
    category: "general",
    difficulty: 3,
    explanation: "El Monte Everest tiene 8,848 metros sobre el nivel del mar en la frontera Nepal-Tíbet.",
    tags: ["geography", "mountains"],
  },
  {
    id: "general_012",
    question: "¿Quién escribió 'Don Quijote de la Mancha'?",
    options: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Garcilaso de la Vega"],
    correctIndex: 1,
    category: "general",
    difficulty: 3,
    explanation: "Miguel de Cervantes publicó Don Quijote en dos partes (1605 y 1615), considerada la primera novela moderna.",
    tags: ["literature", "spain"],
  },
  {
    id: "general_013",
    question: "¿Cuál es el elemento químico más abundante en el universo?",
    options: ["Oxígeno", "Carbono", "Hidrógeno", "Helio"],
    correctIndex: 2,
    category: "general",
    difficulty: 3,
    explanation: "El hidrógeno constituye aproximadamente el 75% de la materia visible del universo.",
    tags: ["chemistry", "space"],
  },
  {
    id: "general_014",
    question: "¿En qué año terminó la Segunda Guerra Mundial?",
    options: ["1943", "1944", "1945", "1946"],
    correctIndex: 2,
    category: "general",
    difficulty: 3,
    explanation: "La WWII terminó en 1945 con la rendición de Alemania (mayo) y Japón (septiembre).",
    tags: ["history", "war"],
  },
  {
    id: "general_015",
    question: "¿Qué país tiene más islas?",
    options: ["Indonesia", "Filipinas", "Suecia", "Japón"],
    correctIndex: 2,
    category: "general",
    difficulty: 3,
    explanation: "Suecia tiene aproximadamente 267,570 islas, más que cualquier otro país.",
    tags: ["geography", "records"],
  },
  // Difficulty 4
  {
    id: "general_016",
    question: "¿Quién fue el primer emperador romano?",
    options: ["Julio César", "Augusto", "Nerón", "Trajano"],
    correctIndex: 1,
    category: "general",
    difficulty: 4,
    explanation: "Augusto (Octavio) fue el primer emperador romano, gobernando desde 27 a.C. hasta 14 d.C.",
    tags: ["history", "rome"],
  },
  {
    id: "general_017",
    question: "¿Qué tratado dividió el mundo entre España y Portugal en 1494?",
    options: ["Tratado de Tordesillas", "Tratado de Westfalia", "Tratado de Versalles", "Tratado de Utrecht"],
    correctIndex: 0,
    category: "general",
    difficulty: 4,
    explanation: "El Tratado de Tordesillas dividió el mundo no descubierto entre las dos potencias ibéricas.",
    tags: ["history", "colonization"],
  },
  {
    id: "general_018",
    question: "¿Cuál es la obra más antigua de la literatura occidental?",
    options: ["La Biblia", "La Ilíada", "La Eneida", "La Odisea"],
    correctIndex: 1,
    category: "general",
    difficulty: 4,
    explanation: "La Ilíada de Homero (siglo VIII a.C.) es considerada la obra literaria más antigua de Occidente.",
    tags: ["literature", "history"],
  },
  {
    id: "general_019",
    question: "¿Qué civilización construyó Machu Picchu?",
    options: ["Azteca", "Maya", "Inca", "Olmeca"],
    correctIndex: 2,
    category: "general",
    difficulty: 4,
    explanation: "Los incas construyeron Machu Picchu en el siglo XV en las montañas de Perú.",
    tags: ["history", "civilizations"],
  },
  // Difficulty 5
  {
    id: "general_020",
    question: "¿Qué filósofo escribió 'El mundo como voluntad y representación'?",
    options: ["Kant", "Nietzsche", "Schopenhauer", "Hegel"],
    correctIndex: 2,
    category: "general",
    difficulty: 5,
    explanation: "Arthur Schopenhauer publicó esta obra fundamental en 1819 sobre filosofía pesimista.",
    tags: ["philosophy", "literature"],
  },
  {
    id: "general_021",
    question: "¿En qué batalla murió Napoleón Bonaparte políticamente?",
    options: ["Austerlitz", "Waterloo", "Trafalgar", "Borodino"],
    correctIndex: 1,
    category: "general",
    difficulty: 5,
    explanation: "Waterloo (1815) fue la derrota final que llevó al exilio de Napoleón en Santa Elena.",
    tags: ["history", "war"],
  },
  {
    id: "general_022",
    question: "¿Qué dinastía construyó la Gran Muralla China?",
    options: ["Han", "Tang", "Ming", "Qin"],
    correctIndex: 3,
    category: "general",
    difficulty: 5,
    explanation: "La dinastía Qin (221-206 a.C.) unificó y comenzó la construcción de la Gran Muralla.",
    tags: ["history", "china"],
  },
];
