/**
 * Gaming trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const gamingQuestions: TriviaQuestion[] = [
  {
    id: "gaming-1",
    question: "In Dark Souls, what does the message 'Try finger, but hole' typically mean?",
    options: ["It's a hint about a hidden path or illusory wall", "It's a warning about a trap", "It's a boss strategy tip", "It means absolutely nothing and that's the point"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "In Dark Souls, player-left messages often hint at illusory walls you can roll or attack through. 'Try finger, but hole' is a classic (if crude) hint about a hidden passage.",
    tags: ["dark-souls", "fromsoft", "humor"],
  },
  {
    id: "gaming-2",
    question: "What is the name of the princess Mario is almost always rescuing?",
    options: ["Princess Peach", "Princess Zelda", "Princess Daisy", "Princess Rosalina"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Princess Peach is Mario's perpetual damsel in distress. She has been kidnapped by Bowser so many times she probably has a frequent flyer card for Bowser's Castle.",
    tags: ["mario", "nintendo", "classics"],
  },
  {
    id: "gaming-3",
    question: "In Minecraft, what happens when you look directly at an Enderman?",
    options: ["It becomes hostile and attacks you", "It teleports away", "It gives you a gift", "It freezes in place"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Looking directly at an Enderman provokes it into attacking. You can avoid this by wearing a pumpkin on your head, which is a completely reasonable fashion choice.",
    tags: ["minecraft", "enderman", "survival"],
  },
  {
    id: "gaming-4",
    question: "What is the Konami Code?",
    options: ["Up Up Down Down Left Right Left Right B A", "A B A B Up Down Left Right Start", "Left Right Up Down A B Select Start", "Up Down Up Down A B B A Start"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Up Up Down Down Left Right Left Right B A — the legendary Konami Code. Originally a cheat in Contra, it's been used in hundreds of games and even some websites.",
    tags: ["konami", "cheat-codes", "classics"],
  },
  {
    id: "gaming-5",
    question: "In Among Us, what does it mean when someone says 'sus'?",
    options: ["They think someone is suspicious (possibly the impostor)", "They want to start a vote", "They found a dead body", "They completed a task"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "'Sus' is short for suspicious. In Among Us, accusing someone of being sus means you think they're the impostor. The word has since escaped the game and infected all of internet culture.",
    tags: ["among-us", "internet-culture", "memes"],
  },
  {
    id: "gaming-6",
    question: "What is the max level in the original Pokémon games (Red/Blue)?",
    options: ["100", "99", "255", "50"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "The max level in Pokémon is 100. However, due to a glitch, Pokémon can reach level 255 before wrapping back to 0. Missingno says hi.",
    tags: ["pokemon", "nintendo", "rpg"],
  },
  {
    id: "gaming-7",
    question: "In The Legend of Zelda, what is Link's name?",
    options: ["Link", "Zelda", "Ganon", "Whatever you typed at the start"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "The protagonist's canonical name is Link. Zelda is the princess. Many people mix them up, which is why Nintendo named the series after the princess instead of the hero — to confuse everyone forever.",
    tags: ["zelda", "nintendo", "classics"],
  },
  {
    id: "gaming-8",
    question: "What does 'GG' mean in gaming?",
    options: ["Good Game", "Get Gud", "Go Again", "Great Grief"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "GG = Good Game. It's a sportsmanship gesture at the end of a match. 'GG EZ' is the opposite of sportsmanship and will get you reported.",
    tags: ["gaming-culture", "slang", "etiquette"],
  },
  {
    id: "gaming-9",
    question: "In what game would you hear 'The cake is a lie'?",
    options: ["Portal", "Half-Life 2", "Bioshock", "Mirror's Edge"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "'The cake is a lie' is from Portal (2007), written on walls by a previous test subject. GLaDOS promises cake as a reward — spoiler: there is no cake. It became one of gaming's most iconic memes.",
    tags: ["portal", "valve", "memes"],
  },
  {
    id: "gaming-10",
    question: "What is a 'speedrun'?",
    options: ["Completing a game as fast as possible, often using glitches", "Running through a game without taking damage", "Playing a game on the highest difficulty", "A competitive racing game genre"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Speedrunning is completing a game as fast as possible. Runners often exploit glitches, wrong warps, and out-of-bounds tricks. The community is incredibly dedicated and slightly unhinged.",
    tags: ["speedrunning", "gaming-culture", "community"],
  },
  {
    id: "gaming-11",
    question: "In Fortnite, what is the name of the storm that forces players together?",
    options: ["The Storm", "The Circle", "The Eye", "The Shrink"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "In Fortnite, 'The Storm' is the deadly zone that shrinks the playable area and forces players into combat. Standing in it deals damage. It's also a great metaphor for deadlines.",
    tags: ["fortnite", "battle-royale", "mechanics"],
  },
  {
    id: "gaming-12",
    question: "What is the name of the main antagonist in the Halo series?",
    options: ["The Gravemind / The Flood", "The Covenant", "The Master Chief", "Cortana"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 2,
    explanation: "The Covenant is the primary antagonist faction in the original Halo trilogy. The Flood is a secondary threat, and the Gravemind is its leader. Master Chief and Cortana are the heroes.",
    tags: ["halo", "xbox", "fps"],
  },
  {
    id: "gaming-13",
    question: "What does 'camping' mean in shooter games?",
    options: ["Staying in one spot to ambush enemies", "Playing outdoors", "Setting up a base of operations", "Hiding until the final circle"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Camping means staying in one spot waiting for enemies to come to you. It's a valid strategy that everyone hates when the enemy does it and defends when they do it.",
    tags: ["fps", "gaming-culture", "strategy"],
  },
  {
    id: "gaming-14",
    question: "In what game does the phrase 'It's dangerous to go alone! Take this.' appear?",
    options: ["The Legend of Zelda (1986)", "Final Fantasy (1987)", "Dragon Quest (1986)", "Metroid (1986)"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "This iconic line is from the original Legend of Zelda (1986), spoken by an old man who gives Link a sword. It's one of the most quoted lines in gaming history.",
    tags: ["zelda", "nintendo", "classics", "quotes"],
  },
  {
    id: "gaming-15",
    question: "What is 'permadeath' in games?",
    options: ["When your character dies permanently and you start over", "A game mode where enemies respawn infinitely", "Dying in-game causes real-world consequences", "A one-hit-kill difficulty setting"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Permadeath means when your character dies, they're gone permanently — no reloading. It's a feature in roguelikes and a source of genuine grief for players everywhere.",
    tags: ["roguelike", "mechanics", "difficulty"],
  },
  {
    id: "gaming-16",
    question: "What is the best-selling video game of all time (as of 2024)?",
    options: ["Minecraft", "GTA V", "Tetris", "Wii Sports"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "Minecraft is the best-selling video game of all time with over 300 million copies sold. It beat Tetris, which held the record for decades. Notch made it in a weekend. (He didn't, but it feels that way.)",
    tags: ["minecraft", "records", "sales"],
  },
  {
    id: "gaming-17",
    question: "In League of Legends, what does 'AFK' mean?",
    options: ["Away From Keyboard (player stopped playing)", "Attack From Keyboard", "Aggressive Farming Kill", "Auto-Fight Kombat"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "AFK = Away From Keyboard. In LoL, an AFK player stops participating, leaving their team at a disadvantage. It's one of the most reported offenses and one of the most common.",
    tags: ["league-of-legends", "moba", "slang"],
  },
  {
    id: "gaming-18",
    question: "What is a 'loot box'?",
    options: ["A randomized reward container purchased with real or in-game currency", "A chest found in the game world with guaranteed loot", "A subscription service for game items", "A box that contains only cosmetic items"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Loot boxes are randomized reward containers, often purchasable with real money. They've been compared to gambling and are banned or regulated in several countries. Publishers call them 'surprise mechanics'.",
    tags: ["monetization", "loot-boxes", "controversy"],
  },
  {
    id: "gaming-19",
    question: "What is the name of the fictional currency in Animal Crossing?",
    options: ["Bells", "Coins", "Nook Miles", "Rupees"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Bells are the main currency in Animal Crossing. You spend them on furniture, tools, and paying off your mortgage to Tom Nook, a raccoon who is either a benevolent landlord or a loan shark depending on who you ask.",
    tags: ["animal-crossing", "nintendo", "currency"],
  },
  {
    id: "gaming-20",
    question: "In Elden Ring, what is the name of the main villain?",
    options: ["Radagon / Elden Beast", "Malenia", "Morgott", "Godfrey"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "The final boss of Elden Ring is Radagon of the Golden Order, who transforms into the Elden Beast. Malenia is the hardest optional boss and the source of much suffering.",
    tags: ["elden-ring", "fromsoft", "bosses"],
  },
  {
    id: "gaming-21",
    question: "What does 'meta' mean in competitive gaming?",
    options: ["The most effective tactics/strategies currently dominant in the game", "A game's story or lore", "A type of in-game currency", "Playing the game ironically"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Meta (Most Effective Tactics Available) refers to the dominant strategies, characters, or builds in a competitive game at a given time. The meta shifts constantly and arguing about it is a full-time job.",
    tags: ["competitive", "meta", "strategy"],
  },
  {
    id: "gaming-22",
    question: "What is a 'No Hit Run' in gaming?",
    options: ["Completing a game without taking any damage", "Completing a game without attacking enemies", "A run where you skip all cutscenes", "Finishing a game with no items"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "A No Hit Run means completing an entire game without taking a single hit of damage. People do this in Dark Souls. These people are not okay.",
    tags: ["challenge-runs", "speedrunning", "skill"],
  },
  {
    id: "gaming-23",
    question: "What is the 'Trolley Problem' equivalent in gaming?",
    options: ["The choice between saving the world or saving one person you love", "Whether to kill an NPC for loot", "Choosing between two equally bad endings", "Deciding whether to use a limited resource now or save it"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Many RPGs present trolley-problem-style moral dilemmas: save the world or save someone you love. Games like Mass Effect and The Witcher built entire systems around these choices.",
    tags: ["rpg", "morality", "game-design"],
  },
  {
    id: "gaming-24",
    question: "What is 'grinding' in RPGs?",
    options: ["Repeatedly doing tasks to gain experience or resources", "Optimizing your character build", "Playing for many hours in one session", "Farming rare item drops"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Grinding means repeatedly doing the same tasks (killing enemies, doing quests) to accumulate XP, currency, or items. It's the video game equivalent of doing homework.",
    tags: ["rpg", "grinding", "mechanics"],
  },
  {
    id: "gaming-25",
    question: "What year was the first PlayStation released in Japan?",
    options: ["1994", "1995", "1996", "1993"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "The original PlayStation launched in Japan on December 3, 1994. It was released in North America in September 1995. It went on to sell 102 million units and cement Sony as a gaming giant.",
    tags: ["playstation", "sony", "history"],
  },
];
