/**
 * Programming trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const programmingQuestions: TriviaQuestion[] = [
  {
    id: "prog-1",
    question: "A developer writes: 'It works on my machine.' What is the industry-standard solution?",
    options: ["Ship the developer's machine", "Use Docker containers", "Blame the QA team", "Rewrite it in Rust"],
    correctIndex: 1,
    category: "programming",
    difficulty: 1,
    explanation: "Docker containers package the app with its environment so it runs the same everywhere. Shipping the developer's machine is also technically correct but frowned upon.",
    tags: ["devops", "docker", "humor"],
  },
  {
    id: "prog-2",
    question: "What does 'null' typically represent in programming?",
    options: ["The absence of a value", "The number zero", "An empty string", "A deleted variable"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Null represents the intentional absence of a value. Tony Hoare, who invented null references, called it his 'billion-dollar mistake'. He wasn't wrong.",
    tags: ["null", "basics", "types"],
  },
  {
    id: "prog-3",
    question: "What is 'recursion' in programming?",
    options: ["A function that calls itself", "A loop that never ends", "Copying code from Stack Overflow twice", "Running the same program on two computers"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Recursion is when a function calls itself. To understand recursion, you must first understand recursion. (See also: this explanation.)",
    tags: ["recursion", "functions", "algorithms"],
  },
  {
    id: "prog-4",
    question: "What is the difference between '==' and '===' in JavaScript?",
    options: ["=== checks value AND type, == does type coercion", "=== is for objects, == is for primitives", "They are identical, one is just older", "=== is three times more equal"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "== does type coercion (so '1' == 1 is true), while === checks both value and type ('1' === 1 is false). Always use === unless you enjoy suffering.",
    tags: ["javascript", "equality", "types"],
  },
  {
    id: "prog-5",
    question: "What is a 'race condition'?",
    options: ["A bug where behavior depends on unpredictable timing of events", "When two programs compete to finish first", "A performance benchmark between languages", "A NASCAR-themed coding challenge"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "A race condition occurs when program behavior depends on the relative timing of events like thread execution. It's a bug that only appears when you're demoing to your boss.",
    tags: ["concurrency", "bugs", "threading"],
  },
  {
    id: "prog-6",
    question: "What does 'DRY' stand for in software development?",
    options: ["Don't Repeat Yourself", "Data Remains Yours", "Deploy Regularly, Yes", "Delete Redundant YAML"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "DRY = Don't Repeat Yourself. Every piece of knowledge should have a single authoritative representation. The opposite is WET: Write Everything Twice (or We Enjoy Typing).",
    tags: ["principles", "dry", "best-practices"],
  },
  {
    id: "prog-7",
    question: "In Git, what does 'git blame' do?",
    options: ["Shows who last modified each line of a file", "Reverts all changes to the last commit", "Deletes the current branch", "Sends an angry email to your team"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "git blame shows who last modified each line and when. It's used for debugging and for passive-aggressively figuring out who wrote that cursed code.",
    tags: ["git", "version-control", "tools"],
  },
  {
    id: "prog-8",
    question: "What is 'spaghetti code'?",
    options: ["Code with tangled, unstructured control flow that's hard to follow", "Code written while hungry", "Python code (it's a pasta language)", "Code that takes too long to execute"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Spaghetti code is a pejorative for code with complex, tangled control flow — like a plate of spaghetti. It's usually found in legacy codebases and your own projects from 3 years ago.",
    tags: ["code-quality", "humor", "anti-patterns"],
  },
  {
    id: "prog-9",
    question: "What does 'API' stand for?",
    options: ["Application Programming Interface", "Automated Program Integrator", "Advanced Protocol Index", "A Pretty Interface"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "API = Application Programming Interface. It's a contract that lets different software talk to each other. REST APIs are the most common, and also the most argued about.",
    tags: ["api", "web", "basics"],
  },
  {
    id: "prog-10",
    question: "What is 'technical debt'?",
    options: ["The cost of choosing a quick solution over a better long-term one", "Money owed to software vendors", "Bugs that haven't been fixed yet", "The time spent in meetings instead of coding"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Technical debt is the implied cost of rework caused by choosing an easy solution now instead of a better approach. It accrues interest and eventually someone has to pay it.",
    tags: ["software-engineering", "technical-debt", "principles"],
  },
  {
    id: "prog-11",
    question: "What is the output of: console.log(0.1 + 0.2) in JavaScript?",
    options: ["0.30000000000000004", "0.3", "0.30", "NaN (Not a Number)"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "Floating point arithmetic strikes again: 0.1 + 0.2 = 0.30000000000000004 in JavaScript (and most languages). This is IEEE 754 floating point, not a JavaScript bug specifically.",
    tags: ["javascript", "floating-point", "gotchas"],
  },
  {
    id: "prog-12",
    question: "What does 'SOLID' stand for in object-oriented design? (First letter only)",
    options: ["Single responsibility, Open/closed, Liskov, Interface segregation, Dependency inversion", "Simple, Organized, Logical, Integrated, Documented", "Scalable, Object-oriented, Linked, Indexed, Dynamic", "It's just one word, not an acronym"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "SOLID: Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion. Five principles for writing maintainable OOP code that you'll argue about forever.",
    tags: ["oop", "solid", "principles"],
  },
  {
    id: "prog-13",
    question: "What is a 'memory leak'?",
    options: ["When a program allocates memory but never frees it", "When RAM physically leaks electricity", "When your code accidentally deletes files", "When a program uses too much RAM at once"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "A memory leak is when a program allocates memory but never releases it, causing memory usage to grow until the program crashes or slows to a crawl. C programmers know this pain intimately.",
    tags: ["memory", "bugs", "performance"],
  },
  {
    id: "prog-14",
    question: "What is 'rubber duck debugging'?",
    options: ["Explaining your code to an inanimate object to find bugs", "Using a rubber duck-shaped USB drive", "A debugging tool in PyCharm", "Pair programming with a junior developer"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Rubber duck debugging: explain your code line-by-line to a rubber duck (or any object). The act of explaining often reveals the bug. It works embarrassingly well.",
    tags: ["debugging", "humor", "techniques"],
  },
  {
    id: "prog-15",
    question: "What does 'async/await' do in modern JavaScript?",
    options: ["Makes asynchronous code look and behave like synchronous code", "Runs code on multiple CPU cores simultaneously", "Delays code execution by a set amount of time", "Prevents the event loop from blocking"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "async/await is syntactic sugar over Promises, making async code read like synchronous code. It doesn't make code run faster — it just makes callback hell look like a distant memory.",
    tags: ["javascript", "async", "promises"],
  },
  {
    id: "prog-16",
    question: "What is the purpose of a 'linter'?",
    options: ["Analyze code for errors, style issues, and bad practices", "Remove unused imports automatically", "Compress code for production", "Check if your code compiles"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "A linter statically analyzes code to flag errors, style violations, and suspicious constructs. It's the friend who tells you your code is messy before you embarrass yourself in a PR.",
    tags: ["tools", "linting", "code-quality"],
  },
  {
    id: "prog-17",
    question: "What is 'Big O notation' used for?",
    options: ["Describing algorithm efficiency as input size grows", "Measuring how surprised a developer is by a bug", "Naming very large numbers in code", "A notation system for object-oriented design"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "Big O notation describes how an algorithm's time or space requirements scale with input size. O(1) is great, O(n²) is a bad time, O(n!) means you're sorting by hand.",
    tags: ["algorithms", "complexity", "big-o"],
  },
  {
    id: "prog-18",
    question: "What does 'refactoring' mean?",
    options: ["Restructuring existing code without changing its behavior", "Rewriting code from scratch", "Fixing bugs in production", "Adding new features to old code"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Refactoring improves code structure without changing what it does. It's the difference between cleaning your room and moving to a new house.",
    tags: ["refactoring", "code-quality", "best-practices"],
  },
  {
    id: "prog-19",
    question: "In Python, what does the 'pass' statement do?",
    options: ["Does absolutely nothing (it's a no-op placeholder)", "Passes a value to the next function", "Skips the current loop iteration", "Exits the current function"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "pass is a no-op statement in Python used as a placeholder where syntax requires a statement but you have nothing to put there yet. It's the 'I'll deal with this later' of Python.",
    tags: ["python", "syntax", "basics"],
  },
  {
    id: "prog-20",
    question: "What is 'dependency injection'?",
    options: ["Providing dependencies to a class from outside rather than creating them internally", "Installing npm packages", "Injecting code into a running process", "A design pattern for managing database connections"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "Dependency injection means a class receives its dependencies from outside (via constructor, method, etc.) rather than creating them itself. It makes testing much easier and your architecture much more debatable.",
    tags: ["design-patterns", "di", "oop"],
  },
  {
    id: "prog-21",
    question: "What is the 'off-by-one error'?",
    options: ["A bug where a loop runs one too many or too few times", "Forgetting to import one library", "A rounding error of exactly 1", "Naming a variable with the wrong index"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Off-by-one errors happen when a loop iterates one too many or too few times, usually from confusing < vs <=. It's one of the most common bugs and also the most embarrassing to explain.",
    tags: ["bugs", "loops", "off-by-one"],
  },
  {
    id: "prog-22",
    question: "What is 'pair programming'?",
    options: ["Two developers working together at one workstation", "Running the same code on two machines", "A technique for debugging with a partner remotely", "Writing code in pairs of functions"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Pair programming has two developers at one machine: one 'drives' (writes code) and one 'navigates' (reviews). It's either incredibly productive or incredibly awkward depending on the pair.",
    tags: ["agile", "pair-programming", "teamwork"],
  },
  {
    id: "prog-23",
    question: "What does 'idempotent' mean in the context of HTTP methods?",
    options: ["Making the same request multiple times has the same effect as making it once", "The request never changes server state", "The response is always the same regardless of input", "The method can be called without authentication"],
    correctIndex: 0,
    category: "programming",
    difficulty: 4,
    explanation: "An idempotent operation produces the same result no matter how many times you call it. GET, PUT, DELETE are idempotent. POST is not — that's why you get 'are you sure you want to resubmit?' warnings.",
    tags: ["http", "rest", "api"],
  },
  {
    id: "prog-24",
    question: "What is 'type inference'?",
    options: ["The compiler automatically deduces the type of a variable", "Manually specifying types in a dynamically typed language", "Inferring what a function does from its name", "A TypeScript-only feature"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "Type inference lets the compiler figure out types without you explicitly annotating them. TypeScript, Rust, and Kotlin all do this. It's like autocomplete but for your type system.",
    tags: ["types", "typescript", "compilers"],
  },
  {
    id: "prog-25",
    question: "What is a 'deadlock' in concurrent programming?",
    options: ["Two or more threads waiting on each other forever, making no progress", "A thread that runs too long and gets killed", "A mutex that can never be unlocked", "When a program freezes due to infinite recursion"],
    correctIndex: 0,
    category: "programming",
    difficulty: 4,
    explanation: "A deadlock is when two or more threads each hold a resource the other needs, so they wait forever. It's like two people in a hallway both stepping aside in the same direction.",
    tags: ["concurrency", "deadlock", "threading"],
  },
];
