/**
 * Gaming Category Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const gamingQuestions: TriviaQuestion[] = [
  // Difficulty 1 - Easy
  {
    id: "gaming_001",
    question: "¿Quién es el protagonista de Super Mario?",
    options: ["Luigi", "Mario", "Bowser", "Toad"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 1,
    explanation: "Mario es el icónico fontanero italiano, mascota de Nintendo y protagonista de la serie Super Mario.",
    tags: ["nintendo", "mario"],
  },
  {
    id: "gaming_002",
    question: "¿En qué juego aparece el personaje Pikachu?",
    options: ["Digimon", "Pokemon", "Zelda", "Mario"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 1,
    explanation: "Pikachu es la mascota de la franquicia Pokemon, criatura eléctrica tipo ratón.",
    tags: ["pokemon", "nintendo"],
  },
  {
    id: "gaming_003",
    question: "¿Qué color es Sonic el Erizo?",
    options: ["Rojo", "Azul", "Verde", "Amarillo"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 1,
    explanation: "Sonic es un erizo azul, mascota de Sega conocido por su velocidad supersónica.",
    tags: ["sega", "sonic"],
  },
  {
    id: "gaming_004",
    question: "¿Qué empresa creó PlayStation?",
    options: ["Microsoft", "Nintendo", "Sony", "Sega"],
    correctIndex: 2,
    category: "gaming",
    difficulty: 1,
    explanation: "Sony creó la consola PlayStation, lanzada por primera vez en 1994 en Japón.",
    tags: ["sony", "playstation", "consoles"],
  },
  {
    id: "gaming_005",
    question: "¿Qué juego popular consiste en colocar bloques que caen?",
    options: ["Pac-Man", "Tetris", "Snake", "Pong"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 1,
    explanation: "Tetris es el juego de puzzle donde debes encajar piezas (tetrominós) que caen.",
    tags: ["puzzle", "classic"],
  },
  {
    id: "gaming_006",
    question: "¿Qué es 'HP' en videojuegos?",
    options: ["Health Points", "Hit Power", "High Performance", "Hero Points"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "HP (Health Points o Hit Points) representa la salud de un personaje en juegos.",
    tags: ["rpg", "basics"],
  },
  {
    id: "gaming_007",
    question: "¿Qué empresa desarrolló Minecraft?",
    options: ["Microsoft", "Mojang", "Roblox Corporation", "Epic Games"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 1,
    explanation: "Mojang (ahora Microsoft) desarrolló Minecraft, creado originalmente por Markus 'Notch' Persson.",
    tags: ["minecraft", "sandbox"],
  },
  {
    id: "gaming_008",
    question: "¿Qué es un 'NPC'?",
    options: ["Non-Player Character", "New Playable Character", "Non-Playable Creature", "Network Player Control"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "NPC (Non-Player Character) es un personaje controlado por la computadora, no por un jugador.",
    tags: ["basics", "rpg"],
  },
  // Difficulty 2
  {
    id: "gaming_009",
    question: "¿Cuál es el objetivo principal en Pac-Man?",
    options: ["Comer todos los puntos", "Derrotar fantasmas", "Llegar al final", "Resolver puzzles"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "En Pac-Man, el objetivo es comer todos los puntos del laberinto mientras evitas fantasmas.",
    tags: ["arcade", "classic"],
  },
  {
    id: "gaming_010",
    question: "¿Qué significa 'GG'?",
    options: ["Good Game", "Great Goal", "Game Over", "Go Go"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "GG (Good Game) es una expresión común al final de partidas multijugador como señal de deportividad.",
    tags: ["slang", "multiplayer"],
  },
  {
    id: "gaming_011",
    question: "¿Qué es un 'speedrun'?",
    options: ["Correr en el juego", "Completar un juego lo más rápido posible", "Un tipo de carrera", "Hackear velocidad"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 2,
    explanation: "Speedrun es completar un videojuego en el menor tiempo posible, a menudo usando técnicas avanzadas.",
    tags: ["speedrun", "community"],
  },
  {
    id: "gaming_012",
    question: "¿En qué año se lanzó el primer World of Warcraft?",
    options: ["2002", "2004", "2006", "2008"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 2,
    explanation: "World of Warcraft se lanzó en 2004, revolucionando los MMORPG masivos.",
    tags: ["blizzard", "mmo", "wow"],
  },
  {
    id: "gaming_013",
    question: "¿Qué es 'lag' en juegos online?",
    options: ["Un tipo de virus", "Retraso en la conexión de red", "Un truco", "Un modo de juego"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 2,
    explanation: "Lag es el retraso entre la acción del jugador y la respuesta del juego, causado por mala conexión.",
    tags: ["networking", "online"],
  },
  {
    id: "gaming_014",
    question: "¿Quién es el creador de Super Smash Bros?",
    options: ["Shigeru Miyamoto", "Masahiro Sakurai", "Hideo Kojima", "Satoru Iwata"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 2,
    explanation: "Masahiro Sakurai creó la serie Super Smash Bros y también es conocido por Kirby.",
    tags: ["nintendo", "developers"],
  },
  // Difficulty 3
  {
    id: "gaming_015",
    question: "¿Qué juego popularizó el género 'battle royale'?",
    options: ["Fortnite", "PUBG", "Apex Legends", "H1Z1"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 3,
    explanation: "PUBG (PlayerUnknown's Battlegrounds) popularizó el género battle royale en 2017.",
    tags: ["battle-royale", "trend"],
  },
  {
    id: "gaming_016",
    question: "¿Qué significa 'DPS' en juegos?",
    options: ["Damage Per Second", "Defense Power Skill", "Double Player Score", "Dungeon Progress Save"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "DPS (Damage Per Second) mide el daño que un personaje puede infligir por segundo.",
    tags: ["rpg", "stats"],
  },
  {
    id: "gaming_017",
    question: "¿Cuál fue el primer videojuego comercialmente exitoso?",
    options: ["Space Invaders", "Pong", "Pac-Man", "Tetris"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 3,
    explanation: "Pong (1972) de Atari fue el primer videojuego comercialmente exitoso, simulando tenis de mesa.",
    tags: ["history", "atari"],
  },
  {
    id: "gaming_018",
    question: "¿Qué es 'The Konami Code'?",
    options: ["Un truco de programación", "Una secuencia de botones famosa", "Un virus", "Un juego"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 3,
    explanation: "El Código Konami (↑↑↓↓←→←→BA) es una secuencia de botones icónica creada por Kazuhisa Hashimoto.",
    tags: ["konami", "easter-egg"],
  },
  {
    id: "gaming_019",
    question: "¿En qué juego aparece la frase 'The cake is a lie'?",
    options: ["Half-Life", "Portal", "BioShock", "Mass Effect"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 3,
    explanation: "'The cake is a lie' es un meme de Portal (2007) que representa falsas promesas del sistema GLaDOS.",
    tags: ["valve", "meme", "quotes"],
  },
  // Difficulty 4
  {
    id: "gaming_020",
    question: "¿Qué significa 'MOBA'?",
    options: ["Multiplayer Online Battle Arena", "Massive Online Battle Action", "Multiplayer Offline Battle Arena", "Mobile Online Battle Action"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 4,
    explanation: "MOBA (Multiplayer Online Battle Arena) es un género que incluye League of Legends y Dota 2.",
    tags: ["moba", "genre"],
  },
  {
    id: "gaming_021",
    question: "¿Qué juego tiene el récord de ventas más alto de la historia?",
    options: ["GTA V", "Minecraft", "Tetris", "Wii Sports"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 4,
    explanation: "Minecraft es el juego más vendido con más de 300 millones de copias vendidas.",
    tags: ["records", "sales"],
  },
  {
    id: "gaming_022",
    question: "¿Qué es 'frame perfect' en speedrunning?",
    options: ["Un glitch", "Una acción que debe hacerse en 1/60 de segundo", "Un truco de hardware", "Un modo de juego"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 4,
    explanation: "Frame perfect significa ejecutar una acción en un frame específico (1/60 segundo a 60fps).",
    tags: ["speedrun", "technical"],
  },
  {
    id: "gaming_023",
    question: "¿Qué compañía desarrolló el motor gráfico Unreal Engine?",
    options: ["Unity Technologies", "Epic Games", "Valve", "id Software"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 4,
    explanation: "Epic Games creó Unreal Engine, usado en Fortnite, Gears of War y muchos otros juegos.",
    tags: ["engines", "epic"],
  },
  // Difficulty 5
  {
    id: "gaming_024",
    question: "¿Qué es 'input lag' vs 'display lag'?",
    options: ["Son lo mismo", "Input es retraso de control, display de pantalla", "Input es de pantalla, display de control", "No existen"],
    correctIndex: 1,
    category: "gaming",
    difficulty: 5,
    explanation: "Input lag es el retraso entre presionar un botón y registrarlo; display lag es el retraso de mostrarlo en pantalla.",
    tags: ["technical", "hardware"],
  },
  {
    id: "gaming_025",
    question: "¿Qué es 'TAS' en speedrunning?",
    options: ["Tool-Assisted Speedrun", "Turbo Action Sequence", "Time Attack Session", "Tool Assisted Sequence"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 5,
    explanation: "TAS (Tool-Assisted Speedrun) usa emulación y savestates para crear runs teóricamente perfectas.",
    tags: ["speedrun", "tas"],
  },
  {
    id: "gaming_026",
    question: "¿Qué es 'subpixel positioning'?",
    options: ["Posicionamiento entre píxeles", "Un tipo de anti-aliasing", "Resolución menor", "Un bug gráfico"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 5,
    explanation: "Subpixel positioning permite posicionar objetos entre píxeles para movimiento más suave.",
    tags: ["technical", "graphics"],
  },
];
