/**
 * Tech trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const techQuestions: TriviaQuestion[] = [
  {
    id: "tech-1",
    question: "You have 8 bits. How many values can you represent before your computer starts judging your life choices?",
    options: ["128", "256", "512", "It depends on your feelings"],
    correctIndex: 1,
    category: "tech",
    difficulty: 1,
    explanation: "8 bits = 2^8 = 256 possible values (0–255). Your computer has no feelings about this.",
    tags: ["binary", "bits", "basics"],
  },
  {
    id: "tech-2",
    question: "What does 'HTTP' stand for? (The S in HTTPS stands for 'safe from your coworkers reading your traffic')",
    options: ["HyperText Transfer Protocol", "High Traffic Transfer Process", "Hyper Terminal Text Program", "How To Transfer Pages"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "HTTP = HyperText Transfer Protocol. The S in HTTPS stands for Secure, not Safe from coworkers.",
    tags: ["networking", "web", "protocols"],
  },
  {
    id: "tech-3",
    question: "Which of these is NOT a real programming language?",
    options: ["Brainfuck", "LOLCODE", "Chicken", "Sadness"],
    correctIndex: 3,
    category: "tech",
    difficulty: 2,
    explanation: "Brainfuck, LOLCODE, and Chicken are all real (and cursed) esoteric programming languages. Sadness is just a feeling.",
    tags: ["programming", "esoteric", "languages"],
  },
  {
    id: "tech-4",
    question: "What happens when you type 'sudo rm -rf /' on a Linux system?",
    options: ["It deletes everything and ruins your day", "It opens a portal to the void", "It asks nicely before deleting", "Nothing, Linux is indestructible"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "sudo rm -rf / recursively force-deletes everything from root. Modern systems add a --no-preserve-root safeguard, but it still ruins your day.",
    tags: ["linux", "terminal", "danger"],
  },
  {
    id: "tech-5",
    question: "What is the correct way to turn off a computer according to IT support?",
    options: ["Have you tried turning it off and on again?", "Unplug it mid-update", "Throw it out the window", "Politely ask it to stop"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "The sacred IT mantra: 'Have you tried turning it off and on again?' fixes roughly 80% of all issues.",
    tags: ["it-support", "humor", "basics"],
  },
  {
    id: "tech-6",
    question: "What is a 'kernel panic' in computing?",
    options: ["When the OS hits a fatal error it can't recover from", "When the CPU gets too hot and starts sweating", "When your code makes the computer cry", "A type of popcorn-related crash"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "A kernel panic is the Linux/macOS equivalent of Windows' Blue Screen of Death — the OS encounters an unrecoverable error.",
    tags: ["os", "linux", "errors"],
  },
  {
    id: "tech-7",
    question: "Which company's logo is a bitten apple? (No, it's not the fruit stand down the street.)",
    options: ["Microsoft", "Apple", "Google", "Amazon"],
    correctIndex: 1,
    category: "tech",
    difficulty: 1,
    explanation: "Apple Inc.'s iconic logo is a bitten apple. The bite is there so it doesn't look like a cherry.",
    tags: ["companies", "logos", "apple"],
  },
  {
    id: "tech-8",
    question: "What does RAM stand for? (Hint: it's not a male sheep.)",
    options: ["Random Access Memory", "Rapid Application Module", "Read And Memorize", "Really Awesome Machine"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "RAM = Random Access Memory. It's your computer's short-term memory — it forgets everything when you turn it off, just like you forget why you walked into a room.",
    tags: ["hardware", "memory", "basics"],
  },
  {
    id: "tech-9",
    question: "What is 'the cloud' actually?",
    options: ["Someone else's computer", "A magical floating storage realm", "A weather phenomenon that stores data", "A very large USB drive in the sky"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "The cloud is just someone else's computer (servers). The joke 'there is no cloud, just other people's computers' is painfully accurate.",
    tags: ["cloud", "internet", "humor"],
  },
  {
    id: "tech-10",
    question: "What is the purpose of a 'firewall' in networking?",
    options: ["Monitor and control incoming/outgoing network traffic", "Keep your computer warm in winter", "Prevent fires from spreading through ethernet cables", "Block your boss from seeing your browser tabs"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "A firewall monitors and controls network traffic based on security rules. It does not, unfortunately, hide your browser tabs from your boss.",
    tags: ["networking", "security", "firewall"],
  },
  {
    id: "tech-11",
    question: "How many bytes are in a kilobyte (in the traditional computing sense)?",
    options: ["1000", "1024", "512", "It depends on who you ask"],
    correctIndex: 1,
    category: "tech",
    difficulty: 2,
    explanation: "Traditionally, 1 KB = 1024 bytes (2^10). The SI definition says 1000, which is why storage manufacturers and your OS always disagree on drive sizes.",
    tags: ["storage", "units", "binary"],
  },
  {
    id: "tech-12",
    question: "What does 'open source' mean?",
    options: ["The source code is publicly available", "The software is free forever, no exceptions", "The code was written with the door open", "It runs on Linux only"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Open source means the source code is publicly available. It doesn't always mean free — but it does mean strangers on the internet will judge your code.",
    tags: ["software", "open-source", "development"],
  },
  {
    id: "tech-13",
    question: "What is 'latency' in networking?",
    options: ["The delay between sending and receiving data", "The speed of your internet connection", "How long your router takes to boot up", "The time it takes to blame your ISP"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Latency is the delay (measured in milliseconds) between sending a request and receiving a response. High latency = lag. Lag = rage.",
    tags: ["networking", "latency", "performance"],
  },
  {
    id: "tech-14",
    question: "What is a 'cookie' in web browsing?",
    options: ["A small file storing user data on your browser", "A reward for visiting a website", "A tracking device implanted by the government", "A delicious snack that websites offer"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Web cookies are small data files stored by your browser to remember your preferences, sessions, and for tracking. Not edible, unfortunately.",
    tags: ["web", "cookies", "privacy"],
  },
  {
    id: "tech-15",
    question: "What does 'VPN' stand for?",
    options: ["Virtual Private Network", "Very Protected Navigation", "Virtually Private Nothing", "Vendor Proxy Node"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "VPN = Virtual Private Network. It encrypts your traffic and routes it through another server. Mostly used for 'accessing geo-restricted content', wink wink.",
    tags: ["networking", "vpn", "privacy"],
  },
  {
    id: "tech-16",
    question: "What is 'phishing'?",
    options: ["Tricking users into revealing sensitive info via fake sites/emails", "A hacking technique that uses actual fish", "Scanning networks for open ports", "Downloading files illegally"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Phishing tricks users into giving up passwords or data via fake emails/sites. It's called phishing because the attacker is fishing for victims. Clever, right?",
    tags: ["security", "phishing", "social-engineering"],
  },
  {
    id: "tech-17",
    question: "What is the main job of a GPU?",
    options: ["Render graphics and parallel computations", "Store your files permanently", "Connect to the internet", "Make your PC louder"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "GPUs (Graphics Processing Units) handle rendering and massively parallel tasks. They also make your PC sound like a jet engine when mining crypto.",
    tags: ["hardware", "gpu", "graphics"],
  },
  {
    id: "tech-18",
    question: "What does 'DNS' stand for?",
    options: ["Domain Name System", "Data Network Service", "Digital Node Server", "Did Nothing Special"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "DNS = Domain Name System. It translates human-readable domain names (google.com) into IP addresses. It's the internet's phone book, except nobody reads phone books.",
    tags: ["networking", "dns", "web"],
  },
  {
    id: "tech-19",
    question: "What is 'bloatware'?",
    options: ["Unwanted pre-installed software that wastes resources", "Software that makes your hard drive physically expand", "A type of malware shaped like a balloon", "Software that only works when you're full"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Bloatware is pre-installed software you didn't ask for and don't want. Every new laptop comes with at least 47 apps you'll never open.",
    tags: ["software", "bloatware", "humor"],
  },
  {
    id: "tech-20",
    question: "What is 'Moore's Law'?",
    options: ["Transistor count on chips doubles roughly every two years", "Every software update makes things slower", "The internet gets 10% more chaotic each year", "Hard drives fill up faster than you can buy new ones"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "Moore's Law (Gordon Moore, 1965) observed that transistor count on chips doubles roughly every two years. It's been slowing down lately, but the chaos law is holding strong.",
    tags: ["hardware", "moores-law", "history"],
  },
  {
    id: "tech-21",
    question: "What is a 'buffer overflow'?",
    options: ["Writing more data to a buffer than it can hold", "When your video buffers for 10 minutes on fast internet", "Overflowing a cup of coffee on your keyboard", "A type of network congestion"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "A buffer overflow occurs when a program writes more data than a buffer can hold, potentially overwriting adjacent memory. It's a classic exploit technique and also why C programmers have trust issues.",
    tags: ["security", "memory", "exploits"],
  },
  {
    id: "tech-22",
    question: "What is 'dark mode' primarily supposed to help with?",
    options: ["Reduce eye strain in low-light environments", "Make your screen invisible to coworkers", "Save battery on OLED screens (and look cool)", "Both A and C"],
    correctIndex: 3,
    category: "tech",
    difficulty: 1,
    explanation: "Dark mode reduces eye strain in low-light conditions AND saves battery on OLED displays (black pixels = off pixels). Also it just looks cooler, let's be honest.",
    tags: ["ui", "dark-mode", "accessibility"],
  },
  {
    id: "tech-23",
    question: "What does 'SSD' stand for?",
    options: ["Solid State Drive", "Super Speed Disk", "Secure Storage Device", "Slightly Speedy Disk"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "SSD = Solid State Drive. No moving parts, much faster than HDDs, and makes your boot time go from 'make a coffee' to 'blink and miss it'.",
    tags: ["hardware", "storage", "ssd"],
  },
  {
    id: "tech-24",
    question: "What is 'two-factor authentication' (2FA)?",
    options: ["Requiring two forms of verification to log in", "Logging in twice to be sure", "Using two passwords instead of one", "Authenticating on two devices simultaneously"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "2FA requires two different verification methods (e.g., password + SMS code). It's annoying until someone tries to hack you, then it's your best friend.",
    tags: ["security", "2fa", "authentication"],
  },
  {
    id: "tech-25",
    question: "What is 'Bluetooth' named after?",
    options: ["Harald Bluetooth, a 10th-century Danish king", "The color of the original prototype device", "A dental condition affecting engineers", "A random name chosen by marketing"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "Bluetooth is named after Harald Bluetooth, a 10th-century Danish king who united Scandinavian tribes — just like Bluetooth unites devices. The logo is his initials in runic script.",
    tags: ["bluetooth", "history", "naming"],
  },
];
