/**
 * Memes & internet culture trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const memeQuestions: TriviaQuestion[] = [
  {
    id: "meme-1",
    question: "What year did the 'This is Fine' dog meme originate from?",
    options: ["2013", "2016", "2011", "2014"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "The 'This is Fine' dog is from KC Green's webcomic 'Gunshow', published in 2013. The dog sits calmly in a burning room saying 'This is fine.' It has aged like fine wine.",
    tags: ["this-is-fine", "webcomic", "history"],
  },
  {
    id: "meme-2",
    question: "What does 'NPC' mean when used to describe a person online?",
    options: ["Someone who seems to lack independent thought or just follows the crowd", "A very skilled gamer", "Someone who plays too many video games", "A person who is very quiet"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "NPC (Non-Player Character) in gaming refers to characters controlled by AI. Online, calling someone an NPC implies they mindlessly follow a script without original thought. It's an insult with a gaming origin.",
    tags: ["npc", "gaming-culture", "internet-slang"],
  },
  {
    id: "meme-3",
    question: "What is a 'rickroll'?",
    options: ["Tricking someone into watching Rick Astley's 'Never Gonna Give You Up'", "Rolling a die in a tabletop game", "A type of bread roll named after Rick", "A prank where you spin someone's chair"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "A rickroll is an internet prank where you share a link that secretly leads to Rick Astley's 'Never Gonna Give You Up' (1987). It's been going strong since 2007 and shows no signs of stopping.",
    tags: ["rickroll", "rick-astley", "pranks"],
  },
  {
    id: "meme-4",
    question: "What does 'based' mean in internet slang?",
    options: ["Holding an opinion confidently regardless of what others think", "Being grounded in reality", "A compliment for being tall", "Having a good foundation for an argument"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Based' originated from rapper Lil B's 'Based' philosophy — being yourself and not caring about others' opinions. Online it evolved to mean confidently holding an opinion, often an unpopular one.",
    tags: ["based", "internet-slang", "lil-b"],
  },
  {
    id: "meme-5",
    question: "What is 'Shrek' primarily associated with in internet culture?",
    options: ["Being an unlikely meme icon and 'love' interest", "A horror movie", "A cooking show parody", "A serious fantasy epic"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "Shrek became an ironic internet icon — 'Shrek is Love, Shrek is Life' being the most notorious example. The internet adopted him as a deity of chaos. DreamWorks did not plan this.",
    tags: ["shrek", "dreamworks", "ironic-memes"],
  },
  {
    id: "meme-6",
    question: "What does 'copypasta' mean?",
    options: ["A block of text repeatedly copied and pasted across the internet", "A type of Italian food meme", "Plagiarized code", "A pasta-themed Discord bot"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "Copypasta is text that gets copy-pasted repeatedly across the internet, often for comedic effect. Famous examples include the Bee Movie script and the 'Navy Seal' pasta.",
    tags: ["copypasta", "internet-culture", "text"],
  },
  {
    id: "meme-7",
    question: "What is the 'Distracted Boyfriend' meme format about?",
    options: ["A man looking at another woman while his girlfriend looks on disapprovingly", "A man ignoring his phone", "A couple arguing about directions", "A man choosing between two jobs"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "The Distracted Boyfriend (stock photo by Antonio Guillem) shows a man ogling another woman while his girlfriend looks horrified. It's used to represent choosing one thing over another you already have.",
    tags: ["distracted-boyfriend", "stock-photo", "format"],
  },
  {
    id: "meme-8",
    question: "What does 'LMAO' stand for?",
    options: ["Laughing My Ass Off", "Laughing Mostly At Others", "Let Me Ask Online", "Loud Memes Are Overrated"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "LMAO = Laughing My Ass Off. It's a step up from LOL. LMFAO adds an F for emphasis. ROFLMAO means you've fallen off your chair, which is a medical emergency.",
    tags: ["acronyms", "internet-slang", "humor"],
  },
  {
    id: "meme-9",
    question: "What is 'Doge'?",
    options: ["A Shiba Inu dog with Comic Sans text describing its thoughts", "A misspelling of 'dog' that became a meme", "A cryptocurrency mascot only", "All of the above"],
    correctIndex: 3,
    category: "memes",
    difficulty: 2,
    explanation: "Doge is all of the above: a Shiba Inu photo with Comic Sans inner monologue text ('much wow', 'very amaze'), a misspelling of 'dog', AND the mascot of Dogecoin. Very meme. Such legacy.",
    tags: ["doge", "shiba-inu", "dogecoin"],
  },
  {
    id: "meme-10",
    question: "What is the 'Two Buttons' meme format typically used to represent?",
    options: ["A person sweating while choosing between two equally difficult options", "A keyboard shortcut tutorial", "A choice between good and evil", "A voting system"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "The 'Two Buttons' meme shows a sweating man hovering over two buttons, unable to choose. It represents the agony of picking between two equally tempting or equally bad options.",
    tags: ["two-buttons", "format", "decisions"],
  },
  {
    id: "meme-11",
    question: "What does 'ratio' mean on Twitter/X?",
    options: ["When a reply gets more likes than the original tweet, implying the reply 'won'", "The number of followers to following ratio", "A metric for tweet engagement", "When you get more retweets than likes"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Getting 'ratioed' means your tweet got more replies than likes — implying people disagreed enough to respond but not enough to like. It's the Twitter equivalent of a slow clap.",
    tags: ["twitter", "ratio", "social-media"],
  },
  {
    id: "meme-12",
    question: "What is 'gaslighting' in internet parlance?",
    options: ["Manipulating someone into questioning their own reality or memory", "Lighting a gas lamp in a historical context", "Sending someone a fake news article", "Trolling someone repeatedly"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Gaslighting (from the 1944 film 'Gaslight') means psychologically manipulating someone into doubting their own perception. It went from psychology term to internet buzzword used for everything from abuse to 'my friend said I was wrong'.",
    tags: ["gaslighting", "psychology", "internet-slang"],
  },
  {
    id: "meme-13",
    question: "What is the 'Galaxy Brain' meme about?",
    options: ["Reaching a conclusion so convoluted it wraps back around to sounding logical", "Having an exceptionally large brain", "A meme about astronomy", "Being very smart at video games"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Galaxy Brain refers to a chain of reasoning so elaborate and convoluted that it arrives at a ridiculous conclusion — but sounds weirdly logical. The meme shows an expanding brain with increasingly absurd takes.",
    tags: ["galaxy-brain", "expanding-brain", "logic"],
  },
  {
    id: "meme-14",
    question: "What does 'touch grass' mean as internet slang?",
    options: ["Go outside and interact with the real world", "Play a nature-themed game", "Calm down and relax", "Delete your social media"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'Touch grass' is advice (often hostile) to go outside and experience the real world. It implies the target has spent too much time online. Ironic that it's most often said online.",
    tags: ["touch-grass", "internet-slang", "advice"],
  },
  {
    id: "meme-15",
    question: "What is 'FOMO'?",
    options: ["Fear Of Missing Out", "Feeling Of Major Overwhelm", "First Order Meme Operation", "Frequency Of Meme Output"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "FOMO = Fear Of Missing Out. The anxiety that others are having more fun or experiencing better things than you. Social media was specifically designed to maximize FOMO. You're welcome.",
    tags: ["fomo", "social-media", "psychology"],
  },
  {
    id: "meme-16",
    question: "What is the 'Stonks' meme?",
    options: ["A deliberately misspelled 'stocks' meme about questionable financial decisions", "A meme about cryptocurrency", "A parody of Wall Street traders", "A meme about building blocks"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'Stonks' features the Meme Man in a suit in front of a stock chart. The deliberate misspelling of 'stocks' is the joke — it's used to celebrate dubious financial wins or losses presented as wins.",
    tags: ["stonks", "finance", "meme-man"],
  },
  {
    id: "meme-17",
    question: "What does 'rent free' mean in internet slang?",
    options: ["Something living in your head that you can't stop thinking about", "Getting free housing", "A meme about landlords", "Being obsessed with someone else's opinion"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Living rent free in your head' means you're obsessed with or can't stop thinking about something/someone. The implication is they're taking up mental real estate without paying for it.",
    tags: ["rent-free", "internet-slang", "obsession"],
  },
  {
    id: "meme-18",
    question: "What is 'Wojak'?",
    options: ["A simple MS Paint-style drawing of a bald man used to express emotions", "A Polish internet celebrity", "A type of reaction image from Reddit", "A Discord bot"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Wojak (from Polish 'wojak' = soldier/warrior) is a simple MS Paint drawing of a bald, sad-looking man. It's spawned hundreds of variants: Doomer, Coomer, NPC, Chad, and more.",
    tags: ["wojak", "reaction-images", "internet-art"],
  },
  {
    id: "meme-19",
    question: "What does 'W' mean in internet slang?",
    options: ["A win or victory", "Wrong", "Whatever", "Weird"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'W' = Win. 'L' = Loss. 'Taking an L' means losing. 'Taking a W' means winning. Entire complex situations are now summarized with single letters. Language is evolving.",
    tags: ["w-l", "internet-slang", "gaming"],
  },
  {
    id: "meme-20",
    question: "What is the 'Drake Approving/Disapproving' meme format?",
    options: ["Drake rejecting one thing and approving another, used to compare preferences", "A meme about the rapper Drake's music", "A format for rating movies", "A meme about door-to-door salesmen"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "The Drake meme uses two panels from his 'Hotline Bling' video: Drake dismissing something (top) and approving something else (bottom). It's used to compare two options and show a preference.",
    tags: ["drake", "hotline-bling", "format"],
  },
  {
    id: "meme-21",
    question: "What does 'lowkey' mean in internet slang?",
    options: ["Secretly or to a moderate degree", "Speaking quietly", "A music term for a low note", "Being introverted"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'Lowkey' means secretly, subtly, or to a moderate degree. 'I lowkey love this song' = I kind of love it but I'm not ready to fully commit to that opinion publicly.",
    tags: ["lowkey", "internet-slang", "casual"],
  },
  {
    id: "meme-22",
    question: "What is 'Pog' or 'PogChamp' in streaming culture?",
    options: ["An expression of excitement or hype, originally a Twitch emote", "A type of card game", "A Twitch streamer's username", "A gaming achievement"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "PogChamp was a Twitch emote showing Ryan 'Gootecks' Gutierrez's excited face. 'Pog' became synonymous with hype and excitement. The original emote was removed in 2021 but 'pog' lives on.",
    tags: ["twitch", "pogchamp", "streaming"],
  },
  {
    id: "meme-23",
    question: "What does 'no cap' mean?",
    options: ["No lie / I'm being serious", "Without a hat", "Not at maximum capacity", "No limitations"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'No cap' means 'no lie' or 'I'm being completely serious'. 'Cap' = lie in AAVE slang. 'That's cap' = that's a lie. 'No cap' = I'm telling the truth. Cap = hat = covering the truth. Maybe.",
    tags: ["no-cap", "aave", "internet-slang"],
  },
  {
    id: "meme-24",
    question: "What is 'main character syndrome'?",
    options: ["Believing you are the protagonist of life and everyone else is an NPC", "A mental health condition", "Being the most important person in a group chat", "Playing only one character in a game"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Main character syndrome is the (often ironic) belief that you're the protagonist of your own story and everyone else exists to serve your narrative. It's either a confidence boost or a red flag depending on severity.",
    tags: ["main-character", "internet-culture", "psychology"],
  },
  {
    id: "meme-25",
    question: "What is 'the void' in internet culture?",
    options: ["An existential emptiness often referenced humorously in memes", "A black hole meme", "A dark web reference", "A Discord server for nihilists"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'The void' represents existential emptiness or nihilism, often referenced humorously. 'Staring into the void' or 'the void stares back' are common formats. It's philosophy for people who don't want to do philosophy.",
    tags: ["void", "existentialism", "humor"],
  },
];
