/**
 * History trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const historyQuestions: TriviaQuestion[] = [
  {
    id: "history-1",
    question: "Napoleon Bonaparte was famously short. How tall was he actually?",
    options: ["About 5'7\" (170 cm) — average for his era", "About 5'2\" (157 cm)", "About 5'4\" (163 cm)", "About 5'9\" (175 cm)"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Napoleon was about 5'7\" (170 cm) — average height for a Frenchman of his time. The 'short Napoleon' myth came from British propaganda and a confusion between French and English inches. He was not short.",
    tags: ["napoleon", "myths", "france"],
  },
  {
    id: "history-2",
    question: "What was the name of the ship that sank on its maiden voyage in 1912?",
    options: ["RMS Titanic", "SS Lusitania", "RMS Mauretania", "SS Olympic"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "The RMS Titanic sank on April 15, 1912, after hitting an iceberg. It was described as 'unsinkable' — which is the kind of thing you should never say about a ship. About 1,500 people died.",
    tags: ["titanic", "disasters", "ships"],
  },
  {
    id: "history-3",
    question: "Which ancient wonder of the world still exists today?",
    options: ["The Great Pyramid of Giza", "The Colossus of Rhodes", "The Hanging Gardens of Babylon", "The Lighthouse of Alexandria"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Great Pyramid of Giza is the only ancient wonder still standing. It was the tallest man-made structure for over 3,800 years. The Hanging Gardens may not have even existed — historians still argue about it.",
    tags: ["ancient-wonders", "egypt", "pyramids"],
  },
  {
    id: "history-4",
    question: "What was the name of the first artificial satellite launched into space?",
    options: ["Sputnik 1", "Explorer 1", "Vostok 1", "Luna 1"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Sputnik 1 was launched by the Soviet Union on October 4, 1957. It beeped. That's all it did. But it terrified the West so much that it started the Space Race and eventually led to humans on the Moon.",
    tags: ["space-race", "soviet-union", "satellites"],
  },
  {
    id: "history-5",
    question: "The Great Wall of China is visible from space. True or false?",
    options: ["False — it's too narrow to see from space", "True — astronauts have confirmed it", "True — but only from low Earth orbit", "False — it doesn't exist in its original form"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Great Wall of China is NOT visible from space with the naked eye. It's too narrow (about 5-8 meters wide). Chinese astronaut Yang Liwei confirmed he couldn't see it. The myth persists anyway.",
    tags: ["great-wall", "china", "myths"],
  },
  {
    id: "history-6",
    question: "What was the name of the first person to walk on the Moon?",
    options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "Neil Armstrong was the first person to walk on the Moon on July 20, 1969. Buzz Aldrin was second. Michael Collins orbited above and is the most overlooked person in one of history's greatest achievements.",
    tags: ["moon-landing", "nasa", "apollo"],
  },
  {
    id: "history-7",
    question: "How long did the Hundred Years' War last?",
    options: ["116 years (1337–1453)", "100 years exactly", "87 years", "150 years"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Hundred Years' War lasted 116 years (1337–1453). Historians grouped it as one conflict for convenience. The Thirty Years' War lasted exactly 30 years. The Seven Years' War lasted 7. History naming is inconsistent.",
    tags: ["hundred-years-war", "france", "england"],
  },
  {
    id: "history-8",
    question: "What was the main cause of the First World War?",
    options: ["A complex web of alliances, nationalism, and the assassination of Archduke Franz Ferdinand", "Germany invading Poland", "The sinking of the Lusitania", "A dispute over colonial territories in Africa"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "WWI was triggered by the assassination of Archduke Franz Ferdinand in 1914, but the real causes were decades of entangled alliances, imperial competition, and nationalism. One bullet started a war that killed 20 million people.",
    tags: ["ww1", "franz-ferdinand", "alliances"],
  },
  {
    id: "history-9",
    question: "Which country was the first to give women the right to vote?",
    options: ["New Zealand (1893)", "Australia (1902)", "Finland (1906)", "United States (1920)"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "New Zealand was the first self-governing country to grant women the right to vote in 1893. Australia followed in 1902. The US didn't achieve it until 1920. Switzerland waited until 1971.",
    tags: ["suffrage", "new-zealand", "women-rights"],
  },
  {
    id: "history-10",
    question: "What was the name of the operation to land Allied troops in Normandy in 1944?",
    options: ["Operation Overlord", "Operation Barbarossa", "Operation Market Garden", "Operation Sea Lion"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Operation Overlord was the codename for the Normandy invasion on June 6, 1944 (D-Day). It was the largest seaborne invasion in history. Operation Barbarossa was Germany's invasion of the USSR.",
    tags: ["ww2", "d-day", "normandy"],
  },
  {
    id: "history-11",
    question: "What empire was ruled by Genghis Khan?",
    options: ["The Mongol Empire", "The Ottoman Empire", "The Tang Dynasty", "The Persian Empire"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "Genghis Khan founded and ruled the Mongol Empire, which became the largest contiguous land empire in history. At its peak it covered 24 million km² — about 22% of Earth's total land area.",
    tags: ["mongol-empire", "genghis-khan", "conquest"],
  },
  {
    id: "history-12",
    question: "What was the name of the plague that killed roughly 1/3 of Europe's population in the 14th century?",
    options: ["The Black Death (Bubonic Plague)", "The Spanish Flu", "The Great Plague of London", "The Antonine Plague"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "The Black Death (1347–1351) killed an estimated 30–60% of Europe's population — up to 50 million people. It was caused by the bacterium Yersinia pestis, spread by fleas on rats. Medieval times were rough.",
    tags: ["black-death", "plague", "medieval"],
  },
  {
    id: "history-13",
    question: "Who was the first Roman Emperor?",
    options: ["Augustus (Octavian)", "Julius Caesar", "Nero", "Caligula"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Augustus (born Octavian) was the first Roman Emperor, ruling from 27 BC. Julius Caesar was never officially emperor — he was Dictator Perpetuo before being stabbed 23 times on the Ides of March.",
    tags: ["rome", "augustus", "emperors"],
  },
  {
    id: "history-14",
    question: "What was the name of the ship Charles Darwin sailed on during his famous voyage?",
    options: ["HMS Beagle", "HMS Endeavour", "HMS Victory", "SS Great Britain"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Darwin sailed on HMS Beagle (1831–1836), visiting the Galápagos Islands among other places. The observations he made on this voyage led to his theory of evolution. The ship's captain was not thrilled with the conclusions.",
    tags: ["darwin", "beagle", "exploration"],
  },
  {
    id: "history-15",
    question: "What year did the Berlin Wall fall?",
    options: ["1989", "1991", "1987", "1990"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Berlin Wall fell on November 9, 1989. It had divided East and West Berlin since 1961. Its fall symbolized the end of the Cold War. Germany was officially reunified on October 3, 1990.",
    tags: ["berlin-wall", "cold-war", "germany"],
  },
  {
    id: "history-16",
    question: "Which ancient civilization built Machu Picchu?",
    options: ["The Inca", "The Aztec", "The Maya", "The Olmec"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "Machu Picchu was built by the Inca Empire around 1450 CE, high in the Andes of Peru. It was abandoned about 100 years later and 'rediscovered' by Hiram Bingham in 1911 — though local people always knew it was there.",
    tags: ["inca", "machu-picchu", "south-america"],
  },
  {
    id: "history-17",
    question: "What was the name of the first printed book in Europe?",
    options: ["The Gutenberg Bible", "The Canterbury Tales", "The Divine Comedy", "The Iliad"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "The Gutenberg Bible (c. 1455) was the first major book printed using movable type in Europe. Johannes Gutenberg's printing press is considered one of the most important inventions in history — it democratized knowledge.",
    tags: ["gutenberg", "printing", "books"],
  },
  {
    id: "history-18",
    question: "What was the name of the first successful powered airplane flight?",
    options: ["The Wright Flyer at Kitty Hawk (1903)", "The Spirit of St. Louis (1927)", "The Hindenburg (1936)", "The Concorde (1969)"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Wright Brothers made the first successful powered airplane flight at Kitty Hawk, North Carolina on December 17, 1903. The flight lasted 12 seconds and covered 37 meters. 66 years later, humans walked on the Moon.",
    tags: ["wright-brothers", "aviation", "invention"],
  },
  {
    id: "history-19",
    question: "What was the name of the treaty that ended World War I?",
    options: ["The Treaty of Versailles", "The Treaty of Paris", "The Treaty of Brest-Litovsk", "The Armistice of Compiègne"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Treaty of Versailles (1919) officially ended WWI. It imposed harsh penalties on Germany — reparations, territorial losses, and war guilt — which many historians argue contributed to the rise of Hitler and WWII.",
    tags: ["ww1", "treaty-of-versailles", "peace"],
  },
  {
    id: "history-20",
    question: "Who was the Egyptian queen famous for her relationships with Julius Caesar and Mark Antony?",
    options: ["Cleopatra VII", "Nefertiti", "Hatshepsut", "Cleopatra VI"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt. She was actually Greek (Macedonian), not Egyptian. She was also reportedly the first Ptolemaic ruler to learn the Egyptian language.",
    tags: ["cleopatra", "egypt", "rome"],
  },
  {
    id: "history-21",
    question: "What was the name of the first country to abolish slavery?",
    options: ["Haiti (1804)", "United Kingdom (1833)", "France (1794)", "United States (1865)"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "Haiti abolished slavery in 1804 after a successful slave revolt — the only successful large-scale slave revolt in history. France had abolished it in 1794 but Napoleon reinstated it in 1802. Haiti made it permanent.",
    tags: ["slavery", "haiti", "abolition"],
  },
  {
    id: "history-22",
    question: "What was the name of the Soviet cosmonaut who was the first human in space?",
    options: ["Yuri Gagarin", "Alexei Leonov", "Valentina Tereshkova", "Sergei Korolev"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "Yuri Gagarin became the first human in space on April 12, 1961, aboard Vostok 1. His flight lasted 108 minutes. He orbited Earth once. He reportedly said 'The Earth is blue... How wonderful. It is amazing.'",
    tags: ["space-race", "gagarin", "soviet-union"],
  },
  {
    id: "history-23",
    question: "What was the name of the ancient library considered the greatest in the ancient world?",
    options: ["The Library of Alexandria", "The Library of Pergamon", "The Library of Nineveh", "The Library of Carthage"],
    correctIndex: 0,
    category: "history",
    difficulty: 2,
    explanation: "The Library of Alexandria in Egypt was the largest library of the ancient world, containing hundreds of thousands of scrolls. Its destruction is one of history's great tragedies — though it declined gradually rather than burning in one dramatic fire.",
    tags: ["alexandria", "library", "ancient"],
  },
  {
    id: "history-24",
    question: "What was the name of the first country to use paper money?",
    options: ["China (Tang Dynasty, ~7th century)", "Italy (13th century)", "Sweden (17th century)", "England (17th century)"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "China invented paper money during the Tang Dynasty (~7th century CE). It was called 'flying money' because it was so light it could blow away. Europe didn't adopt paper currency until the 17th century.",
    tags: ["china", "money", "invention"],
  },
  {
    id: "history-25",
    question: "What was the name of the ship on which the Pilgrims sailed to America in 1620?",
    options: ["The Mayflower", "The Santa Maria", "The Endeavour", "The Speedwell"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "The Pilgrims sailed on the Mayflower in 1620, landing at Plymouth Rock. The Speedwell was supposed to accompany it but kept leaking. The Mayflower carried 102 passengers on a 66-day voyage.",
    tags: ["mayflower", "pilgrims", "america"],
  },
];
