/**
 * General knowledge trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const generalQuestions: TriviaQuestion[] = [
  {
    id: "general-1",
    question: "If you're in a room with 23 people, what's the probability that two of them share a birthday? (Roughly)",
    options: ["About 50%", "About 10%", "About 90%", "About 1%"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Birthday Paradox: with just 23 people, there's roughly a 50% chance two share a birthday. With 70 people it's 99.9%. Human intuition is terrible at probability.",
    tags: ["probability", "math", "birthday-paradox"],
  },
  {
    id: "general-2",
    question: "How many times can you fold a piece of paper in half?",
    options: ["About 7 times", "Unlimited, if you're strong enough", "Exactly 10 times", "About 3 times"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "In practice, you can fold a standard piece of paper about 7 times before it becomes too thick. In theory, the 42nd fold would reach the Moon. Paper is deceptively powerful.",
    tags: ["paper-folding", "math", "fun-facts"],
  },
  {
    id: "general-3",
    question: "What is the shortest war in recorded history?",
    options: ["The Anglo-Zanzibar War (38-45 minutes)", "The Six-Day War (6 days)", "The Football War (100 hours)", "The Falklands War (74 days)"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Anglo-Zanzibar War of 1896 lasted between 38 and 45 minutes. Zanzibar surrendered almost immediately. It remains the shortest war in recorded history.",
    tags: ["history", "wars", "records"],
  },
  {
    id: "general-4",
    question: "What percentage of the ocean has been explored by humans?",
    options: ["About 20%", "About 80%", "About 5%", "About 50%"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Only about 20% of the ocean has been mapped or explored. We know more about the surface of Mars than our own ocean floor. The ocean is enormous and very wet.",
    tags: ["ocean", "exploration", "science"],
  },
  {
    id: "general-5",
    question: "How many bones does an adult human body have?",
    options: ["206", "212", "198", "256"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Adults have 206 bones. Babies are born with around 270-300 bones that fuse together as they grow. You had more bones as a baby and somehow that's not the weirdest fact about you.",
    tags: ["anatomy", "human-body", "biology"],
  },
  {
    id: "general-6",
    question: "What is the most spoken language in the world by total speakers?",
    options: ["English", "Mandarin Chinese", "Spanish", "Hindi"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "English has the most total speakers (native + second language) at roughly 1.5 billion. Mandarin has the most native speakers. English colonized the world and then colonized the internet.",
    tags: ["languages", "linguistics", "world"],
  },
  {
    id: "general-7",
    question: "A group of flamingos is called a what?",
    options: ["A flamboyance", "A flock", "A pink", "A flamingle"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "A group of flamingos is called a 'flamboyance'. This is the most accurate collective noun in the English language. Other great ones: a murder of crows, a parliament of owls.",
    tags: ["animals", "collective-nouns", "vocabulary"],
  },
  {
    id: "general-8",
    question: "What is the speed of light (approximately)?",
    options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "30,000 km/s"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Light travels at approximately 299,792 km/s (roughly 300,000 km/s). It takes about 8 minutes for sunlight to reach Earth. Nothing travels faster — it's the universe's speed limit.",
    tags: ["physics", "light", "science"],
  },
  {
    id: "general-9",
    question: "How many sides does a dodecagon have?",
    options: ["12", "10", "8", "14"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "A dodecagon has 12 sides. 'Dodeca' is Greek for 12. A dodecahedron has 12 faces. The UK 50p coin is a heptagon (7 sides) because the Royal Mint likes to be different.",
    tags: ["geometry", "math", "shapes"],
  },
  {
    id: "general-10",
    question: "What is the longest river in the world?",
    options: ["The Nile", "The Amazon", "The Yangtze", "The Mississippi"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "The Nile is traditionally considered the longest river at ~6,650 km. The Amazon is a close second and some measurements put it first. Geographers argue about this constantly.",
    tags: ["geography", "rivers", "world"],
  },
  {
    id: "general-11",
    question: "What is the most common element in the universe?",
    options: ["Hydrogen", "Oxygen", "Carbon", "Helium"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Hydrogen makes up about 75% of all normal matter in the universe. Helium is second at about 24%. Everything else — including you — is cosmic rounding error.",
    tags: ["chemistry", "universe", "elements"],
  },
  {
    id: "general-12",
    question: "How long does it take for the Earth to orbit the Sun?",
    options: ["365.25 days", "365 days exactly", "366 days", "364 days"],
    correctIndex: 0,
    category: "general",
    difficulty: 1,
    explanation: "Earth's orbit takes 365.25 days, which is why we add a leap day every 4 years. Even that's not exact — we skip leap years on century years unless divisible by 400. Calendars are a mess.",
    tags: ["astronomy", "earth", "time"],
  },
  {
    id: "general-13",
    question: "What is the capital of Australia?",
    options: ["Canberra", "Sydney", "Melbourne", "Brisbane"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Canberra is Australia's capital. Sydney and Melbourne both wanted to be capital so badly that Australia built an entirely new city between them as a compromise. Democracy is wild.",
    tags: ["geography", "capitals", "australia"],
  },
  {
    id: "general-14",
    question: "What is the hardest natural substance on Earth?",
    options: ["Diamond", "Graphene", "Corundum (Ruby/Sapphire)", "Tungsten"],
    correctIndex: 0,
    category: "general",
    difficulty: 1,
    explanation: "Diamond is the hardest natural substance (10 on the Mohs scale). Graphene is stronger but synthetic. Diamonds are made of carbon — the same element as pencil lead, just under extreme pressure.",
    tags: ["materials", "science", "minerals"],
  },
  {
    id: "general-15",
    question: "How many colors are in a rainbow?",
    options: ["7 (traditionally)", "6", "Infinite", "It depends on the rainbow"],
    correctIndex: 2,
    category: "general",
    difficulty: 3,
    explanation: "A rainbow is actually a continuous spectrum of infinite colors. We traditionally say 7 (ROY G BIV) because Isaac Newton decided on 7 to match musical notes. The 'indigo' is basically just dark blue.",
    tags: ["physics", "light", "colors"],
  },
  {
    id: "general-16",
    question: "What is the smallest country in the world?",
    options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"],
    correctIndex: 0,
    category: "general",
    difficulty: 1,
    explanation: "Vatican City is the world's smallest country at 0.44 km². It's entirely within Rome, has its own postal system, and is ruled by the Pope. It's also the world's smallest country with a Swiss Guard.",
    tags: ["geography", "countries", "records"],
  },
  {
    id: "general-17",
    question: "What is the most expensive spice in the world by weight?",
    options: ["Saffron", "Vanilla", "Cardamom", "Truffle"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Saffron can cost up to $10,000 per kilogram. It comes from the stigmas of crocus flowers, harvested by hand. Each flower produces only 3 stigmas. It takes 75,000 flowers to make one pound.",
    tags: ["food", "spices", "economics"],
  },
  {
    id: "general-18",
    question: "What does 'E pluribus unum' (on US currency) mean?",
    options: ["Out of many, one", "In God we trust", "United we stand", "Freedom above all"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "'E pluribus unum' is Latin for 'Out of many, one' — referring to the many states forming one nation. It was the de facto US motto until 1956 when 'In God We Trust' was officially adopted.",
    tags: ["latin", "usa", "history"],
  },
  {
    id: "general-19",
    question: "How many hearts does an octopus have?",
    options: ["3", "1", "2", "4"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Octopuses have 3 hearts: two pump blood to the gills, one pumps it to the body. They also have blue blood (copper-based) and 9 brains (one central + one per arm). Octopuses are deeply unreasonable creatures.",
    tags: ["animals", "biology", "octopus"],
  },
  {
    id: "general-20",
    question: "What is the most recycled material in the world?",
    options: ["Steel/Iron", "Aluminum", "Paper", "Glass"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Steel and iron are the most recycled materials globally by volume. Aluminum is the most recycled packaging material. Recycling a single aluminum can saves enough energy to run a TV for 3 hours.",
    tags: ["environment", "recycling", "materials"],
  },
  {
    id: "general-21",
    question: "What is the Fermi Paradox?",
    options: ["If aliens exist, why haven't we heard from them?", "Why can't we travel faster than light?", "Why does the universe exist at all?", "Why is there more matter than antimatter?"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Fermi Paradox asks: given the high probability of extraterrestrial civilizations, why haven't we detected any? Either we're alone, they're hiding, or they all destroy themselves. Cheerful stuff.",
    tags: ["astronomy", "philosophy", "aliens"],
  },
  {
    id: "general-22",
    question: "What is the most common phobia?",
    options: ["Arachnophobia (fear of spiders)", "Acrophobia (fear of heights)", "Claustrophobia (fear of small spaces)", "Agoraphobia (fear of open spaces)"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Arachnophobia (fear of spiders) is consistently ranked as the most common phobia. About 3-15% of the population has it. Spiders are mostly harmless but have apparently done excellent PR for fear.",
    tags: ["psychology", "phobias", "spiders"],
  },
  {
    id: "general-23",
    question: "What is the Dunning-Kruger effect?",
    options: ["People with low competence overestimate their ability", "Experts underestimate how difficult their field is", "The more you know, the less confident you become", "Smart people are bad at explaining things"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Dunning-Kruger effect: people with limited knowledge in a domain overestimate their competence. Experts, knowing how much they don't know, often underestimate themselves. The internet is a Dunning-Kruger factory.",
    tags: ["psychology", "cognitive-bias", "dunning-kruger"],
  },
  {
    id: "general-24",
    question: "What is the most common surname in the world?",
    options: ["Wang (China)", "Smith (English)", "Garcia (Spanish)", "Kim (Korean)"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Wang is the most common surname in the world, with over 100 million people sharing it in China alone. China's population size means Chinese surnames dominate global surname statistics.",
    tags: ["names", "demographics", "world"],
  },
  {
    id: "general-25",
    question: "What is the Mandela Effect?",
    options: ["A phenomenon where many people share the same false memory", "The effect Nelson Mandela had on global politics", "A cognitive bias named after a South African leader", "When historical events are misattributed to the wrong person"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "The Mandela Effect is when large groups of people share the same false memory — named after many people falsely 'remembering' Nelson Mandela dying in prison in the 1980s. He died in 2013. The Monopoly man never had a monocle.",
    tags: ["psychology", "memory", "mandela-effect"],
  },
];
