/**
 * Extra Questions to reach 250+ total.
 */

import type { TriviaQuestion } from "./types";

export const extraQuestions: TriviaQuestion[] = [
  // Tech extras
  {
    id: "tech_extra_001",
    question: "¿Qué es 'malware'?",
    options: ["Software malicioso", "Software de marketing", "Un antivirus", "Un sistema operativo"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Malware (malicious software) incluye virus, troyanos, ransomware y spyware.",
    tags: ["security"],
  },
  {
    id: "tech_extra_002",
    question: "¿Qué es 'Bluetooth'?",
    options: ["Tecnología inalámbrica de corto alcance", "Un tipo de cable", "Una red 5G", "Un protocolo de email"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Bluetooth permite conectar dispositivos cercanos sin cables (auriculares, teclados, etc.).",
    tags: ["wireless"],
  },
  {
    id: "tech_extra_003",
    question: "¿Qué es 'phishing'?",
    options: ["Estafa para robar datos personales", "Un tipo de pesca", "Un virus", "Un firewall"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Phishing usa emails o sitios falsos para engañar y robar contraseñas o información.",
    tags: ["security"],
  },
  {
    id: "tech_extra_004",
    question: "¿Qué es '4K' en pantallas?",
    options: ["Resolución de ~4000 píxeles de ancho", "Un tipo de procesador", "Una marca", "Un formato de audio"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "4K UHD tiene 3840x2160 píxeles, cuatro veces la resolución Full HD 1080p.",
    tags: ["display"],
  },
  {
    id: "tech_extra_005",
    question: "¿Qué es 'machine learning'?",
    options: ["Aprendizaje automático por computadoras", "Memoria RAM", "Un tipo de CPU", "Un sistema operativo"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "Machine learning permite a las computadoras aprender patrones de datos sin programación explícita.",
    tags: ["ai"],
  },
  // Gaming extras
  {
    id: "gaming_extra_001",
    question: "¿Qué es 'FPS' en juegos?",
    options: ["Frames Per Second / First Person Shooter", "Fast Player Speed", "Final Play Score", "First Play Session"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "FPS puede significar Frames Per Second (fluidez) o First Person Shooter (género).",
    tags: ["terminology"],
  },
  {
    id: "gaming_extra_002",
    question: "¿Qué es 'lag'?",
    options: ["Retraso en la conexión", "Un truco", "Un modo de juego", "Un tipo de joystick"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 1,
    explanation: "Lag es el retraso entre la acción del jugador y la respuesta en pantalla.",
    tags: ["networking"],
  },
  {
    id: "gaming_extra_003",
    question: "¿Qué es un 'easter egg'?",
    options: ["Secreto oculto en un juego", "Un tipo de huevo", "Un personaje", "Un nivel"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Los easter eggs son secretos, mensajes ocultos o referencias que los desarrolladores esconden.",
    tags: ["culture"],
  },
  {
    id: "gaming_extra_004",
    question: "¿Qué es 'DLC'?",
    options: ["Downloadable Content", "Digital Level Code", "Direct Line Connection", "Data Load Complete"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "DLC es contenido descargable: expansiones, skins, mapas adicionales para un juego.",
    tags: ["business"],
  },
  {
    id: "gaming_extra_005",
    question: "¿Qué es 'pay to win'?",
    options: ["Juego donde pagar da ventajas", "Juego gratis", "Juego de suscripción", "Juego de carreras"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "'Pay to win' critica juegos donde gastar dinero real da ventajas competitivas significativas.",
    tags: ["business", "culture"],
  },
  // Anime extras
  {
    id: "anime_extra_001",
    question: "¿Qué es 'manga'?",
    options: ["Cómics japoneses", "Anime de acción", "Música japonesa", "Comida japonesa"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Manga son los cómics o novelas gráficas japonesas, generalmente en blanco y negro.",
    tags: ["terminology"],
  },
  {
    id: "anime_extra_002",
    question: "¿Qué significa 'kawaii'?",
    options: ["Bonito/cute", "Fuerte", "Rápido", "Grande"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Kawaii (可愛い) significa 'bonito', 'tierno' o 'cute' en japonés.",
    tags: ["terminology"],
  },
  {
    id: "anime_extra_003",
    question: "¿Qué es 'otaku'?",
    options: ["Fanático de anime/manga", "Artista de anime", "Director de anime", "Actor de voz"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Otaku (オタク) se refiere a personas con interés obsesivo en anime, manga o videojuegos.",
    tags: ["culture"],
  },
  {
    id: "anime_extra_004",
    question: "¿Qué es 'isekai'?",
    options: ["Género de transporte a otro mundo", "Un estudio de anime", "Un tipo de sushi", "Un personaje"],
    correctIndex: 0,
    category: "anime",
    difficulty: 3,
    explanation: "Isekai (異世界) significa 'otro mundo', género donde personajes se transportan a mundos diferentes.",
    tags: ["genre"],
  },
  // Programming extras
  {
    id: "prog_extra_001",
    question: "¿Qué es 'debugging'?",
    options: ["Encontrar y corregir errores", "Escribir código", "Compilar programa", "Diseñar interfaz"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Debugging es el proceso de encontrar y eliminar errores (bugs) del código.",
    tags: ["basics"],
  },
  {
    id: "prog_extra_002",
    question: "¿Qué es 'open source'?",
    options: ["Software con código público", "Software gratuito", "Software privado", "Software de pago"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Open source significa que el código fuente está disponible para que cualquiera lo vea o modifique.",
    tags: ["culture"],
  },
  {
    id: "prog_extra_003",
    question: "¿Qué es un 'bug'?",
    options: ["Error en el código", "Característica", "Comentario", "Variable"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "Un bug es un error o defecto en el código que produce resultados incorrectos.",
    tags: ["basics"],
  },
  {
    id: "prog_extra_004",
    question: "¿Qué lenguaje se usa para páginas web interactivas?",
    options: ["HTML", "CSS", "JavaScript", "SQL"],
    correctIndex: 2,
    category: "programming",
    difficulty: 1,
    explanation: "JavaScript es el lenguaje de programación que agrega interactividad a las páginas web.",
    tags: ["web"],
  },
  // General extras
  {
    id: "general_extra_001",
    question: "¿Cuál es la capital de Francia?",
    options: ["Londres", "Berlín", "París", "Madrid"],
    correctIndex: 2,
    category: "general",
    difficulty: 1,
    explanation: "París es la capital de Francia, conocida como la 'Ciudad de la Luz'.",
    tags: ["geography"],
  },
  {
    id: "general_extra_002",
    question: "¿Cuántos días tiene un año bisiesto?",
    options: ["365", "366", "364", "367"],
    correctIndex: 1,
    category: "general",
    difficulty: 1,
    explanation: "Los años bisiestos tienen 366 días, añadiendo un día extra (29 de febrero) cada 4 años.",
    tags: ["calendar"],
  },
  {
    id: "general_extra_003",
    question: "¿Qué idioma se habla en Brasil?",
    options: ["Español", "Portugués", "Francés", "Inglés"],
    correctIndex: 1,
    category: "general",
    difficulty: 1,
    explanation: "En Brasil se habla portugués, legado de la colonización portuguesa.",
    tags: ["language", "geography"],
  },
  {
    id: "general_extra_004",
    question: "¿Qué es el 'Big Ben'?",
    options: ["Un reloj en Londres", "Un puente", "Un palacio", "Una torre en París"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Big Ben es la gran campana del reloj del Palacio de Westminster en Londres.",
    tags: ["landmarks"],
  },
  // Science extras
  {
    id: "science_extra_001",
    question: "¿Qué planeta es conocido como el planeta rojo?",
    options: ["Venus", "Marte", "Júpiter", "Saturno"],
    correctIndex: 1,
    category: "science",
    difficulty: 1,
    explanation: "Marte es el planeta rojo debido al óxido de hierro (herrumbre) en su superficie.",
    tags: ["astronomy"],
  },
  {
    id: "science_extra_002",
    question: "¿Cuál es el hueso más largo del cuerpo humano?",
    options: ["Fémur", "Húmero", "Tibia", "Radio"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "El fémur, en el muslo, es el hueso más largo y fuerte del cuerpo humano.",
    tags: ["biology"],
  },
  {
    id: "science_extra_003",
    question: "¿Qué es la fotosíntesis?",
    options: ["Proceso de conversión de luz en energía", "Proceso digestivo", "Reproducción celular", "Respiración"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "La fotosíntesis convierte luz solar, agua y CO2 en glucosa y oxígeno en las plantas.",
    tags: ["biology"],
  },
  // History extras
  {
    id: "history_extra_001",
    question: "¿Quién pintó la Mona Lisa?",
    options: ["Van Gogh", "Picasso", "Leonardo da Vinci", "Miguel Ángel"],
    correctIndex: 2,
    category: "history",
    difficulty: 1,
    explanation: "Leonardo da Vinci pintó la Mona Lisa entre 1503 y 1519.",
    tags: ["art"],
  },
  {
    id: "history_extra_002",
    question: "¿En qué año terminó la Segunda Guerra Mundial?",
    options: ["1943", "1944", "1945", "1946"],
    correctIndex: 2,
    category: "history",
    difficulty: 2,
    explanation: "La Segunda Guerra Mundial terminó en 1945 con la rendición de Alemania y Japón.",
    tags: ["war"],
  },
  // Music extras
  {
    id: "music_extra_001",
    question: "¿Cuántas teclas tiene un piano estándar?",
    options: ["66", "88", "72", "96"],
    correctIndex: 1,
    category: "music",
    difficulty: 2,
    explanation: "Un piano estándar tiene 88 teclas: 52 blancas y 36 negras.",
    tags: ["instruments"],
  },
  {
    id: "music_extra_002",
    question: "¿Qué instrumento tiene cuerdas?",
    options: ["Flauta", "Guitarra", "Batería", "Trompeta"],
    correctIndex: 1,
    category: "music",
    difficulty: 1,
    explanation: "La guitarra es un instrumento de cuerda pulsada muy popular en música popular.",
    tags: ["instruments"],
  },
  // Meme extras
  {
    id: "meme_extra_001",
    question: "¿Qué significa 'F' en los chats?",
    options: ["Respeto/luto", "Felicitaciones", "Fracaso", "Final"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'F' viene de Call of Duty donde se presiona F para 'pay respects' (rendir respetos).",
    tags: ["culture"],
  },
  {
    id: "meme_extra_002",
    question: "¿Qué es 'ratio' en Twitter/X?",
    options: ["Tener más respuestas que likes", "Una proporción matemática", "Un tipo de imagen", "Un video viral"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "'Ratio' ocurre cuando un tweet tiene más respuestas (generalmente negativas) que likes.",
    tags: ["culture", "twitter"],
  },
  {
    id: "meme_extra_003",
    question: "¿Qué significa 'L' en gaming?",
    options: ["Loss/derrota", "Left/izquierda", "Level/nivel", "Legend/leyenda"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "'L' significa 'Loss' (derrota), opuesto a 'W' (Win/victoria).",
    tags: ["gaming", "slang"],
  },
  {
    id: "meme_extra_004",
    question: "¿Qué es 'main character syndrome'?",
    options: ["Creerse protagonista de la vida", "Jugar RPGs", "Ver películas", "Escribir historias"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Main character syndrome' es cuando alguien se comporta como si fuera el protagonista de todo.",
    tags: ["culture"],
  },
  // Tech more extras
  {
    id: "tech_extra_006",
    question: "¿Qué es '2FA'?",
    options: ["Autenticación de dos factores", "Un tipo de archivo", "Un protocolo de red", "Un sistema operativo"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "2FA (Two-Factor Authentication) añade una segunda capa de seguridad al iniciar sesión.",
    tags: ["security"],
  },
  {
    id: "tech_extra_007",
    question: "¿Qué es 'NFT'?",
    options: ["Token no fungible", "Un tipo de criptomoneda", "Un formato de imagen", "Una red social"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "NFT (Non-Fungible Token) es un certificado digital de propiedad único en blockchain.",
    tags: ["crypto", "blockchain"],
  },
  // Gaming more extras
  {
    id: "gaming_extra_006",
    question: "¿Qué es 'smurfing' en juegos competitivos?",
    options: ["Jugar en cuenta de menor nivel", "Usar trampas", "Desconectarse", "Hacer equipo"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 3,
    explanation: "Un 'smurf' es un jugador experimentado que usa cuenta de bajo nivel para enfrentar novatos.",
    tags: ["competitive"],
  },
  {
    id: "gaming_extra_007",
    question: "¿Qué es 'griefing'?",
    options: ["Molestar intencionalmente a compañeros", "Perder una partida", "Jugar solo", "Usar chat de voz"],
    correctIndex: 0,
    category: "gaming",
    difficulty: 2,
    explanation: "Griefing es sabotear intencionalmente la experiencia de juego de compañeros de equipo.",
    tags: ["behavior"],
  },
  // Anime more extras
  {
    id: "anime_extra_005",
    question: "¿Qué significa 'senpai'?",
    options: ["Persona de mayor experiencia/graduación", "Maestro", "Estudiante", "Amigo"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Senpai (先輩) se refiere a alguien con más experiencia en una escuela u organización.",
    tags: ["terminology"],
  },
  {
    id: "anime_extra_006",
    question: "¿Qué es 'waifu'?",
    options: ["Personaje femenino favorito", "Una esposa real", "Una actriz", "Una cantante"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "'Waifu' es un personaje femenino de ficción por el que alguien siente gran afecto.",
    tags: ["culture"],
  },
  // Programming more extras
  {
    id: "prog_extra_005",
    question: "¿Qué es un 'algorithm'?",
    options: ["Conjunto de pasos para resolver un problema", "Un tipo de computadora", "Un lenguaje de programación", "Un sistema operativo"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Un algoritmo es una secuencia finita de instrucciones para resolver un problema específico.",
    tags: ["basics"],
  },
  {
    id: "prog_extra_006",
    question: "¿Qué es 'frontend' en desarrollo web?",
    options: ["Parte visible/interfaz de usuario", "Base de datos", "Servidor", "Seguridad"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "Frontend es todo lo que el usuario ve e interactúa en una aplicación web.",
    tags: ["web"],
  },
  // General more extras
  {
    id: "general_extra_005",
    question: "¿Cuál es el metal más abundante en la corteza terrestre?",
    options: ["Hierro", "Aluminio", "Cobre", "Oro"],
    correctIndex: 1,
    category: "general",
    difficulty: 3,
    explanation: "El aluminio es el metal más abundante, aunque nunca se encuentra puro en la naturaleza.",
    tags: ["chemistry"],
  },
  {
    id: "general_extra_006",
    question: "¿Qué país tiene forma de bota?",
    options: ["España", "Italia", "Grecia", "Francia"],
    correctIndex: 1,
    category: "general",
    difficulty: 1,
    explanation: "Italia es conocida por su forma característica de bota en el mapa.",
    tags: ["geography"],
  },
  // Science more extras
  {
    id: "science_extra_004",
    question: "¿Qué es el 'oxígeno'?",
    options: ["Elemento químico O", "Un gas noble", "Un metal", "Un compuesto"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "El oxígeno (O) es el elemento químico esencial para la respiración y combustión.",
    tags: ["chemistry"],
  },
  {
    id: "science_extra_005",
    question: "¿Cuántos huesos tiene un adulto humano?",
    options: ["106", "206", "306", "256"],
    correctIndex: 1,
    category: "science",
    difficulty: 2,
    explanation: "Un adulto humano tiene 206 huesos (los bebés nacen con aproximadamente 270).",
    tags: ["biology"],
  },
  // History more extras
  {
    id: "history_extra_003",
    question: "¿Quién fue Albert Einstein?",
    options: ["Físico teórico famoso", "Un presidente", "Un pintor", "Un músico"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "Einstein (1879-1955) desarrolló la teoría de la relatividad y ganó el Nobel de Física.",
    tags: ["science"],
  },
  {
    id: "history_extra_004",
    question: "¿Qué era el Titanic?",
    options: ["Un barco transatlántico", "Un avión", "Un tren", "Un puente"],
    correctIndex: 0,
    category: "history",
    difficulty: 1,
    explanation: "El Titanic fue un transatlántico que se hundió en 1912 tras chocar con un iceberg.",
    tags: ["transport"],
  },
  // Music more extras
  {
    id: "music_extra_003",
    question: "¿Qué es un 'álbum' musical?",
    options: ["Colección de canciones", "Una sola canción", "Un concierto", "Un instrumento"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Un álbum es una colección de canciones publicadas juntas, típicamente 10-15 pistas.",
    tags: ["industry"],
  },
  {
    id: "music_extra_004",
    question: "¿Qué instrumento toca un pianista?",
    options: ["Guitarra", "Piano", "Violín", "Batería"],
    correctIndex: 1,
    category: "music",
    difficulty: 1,
    explanation: "Un pianista toca el piano, instrumento de teclado percusivo.",
    tags: ["instruments"],
  },
  // Meme more extras
  {
    id: "meme_extra_005",
    question: "¿Qué significa 'simp'?",
    options: ["Persona que busca aprobación desesperadamente", "Un tipo simple", "Un juego", "Una app"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Simp' describe a alguien que busca atención o aprobación de manera excesiva, especialmente romántica.",
    tags: ["slang"],
  },
  {
    id: "meme_extra_006",
    question: "¿Qué es 'cringe'?",
    options: ["Vergüenza ajena o pena", "Alegría", "Enojo", "Tristeza"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Cringe' describe la vergüenza ajena que sientes al ver algo embarazoso.",
    tags: ["slang"],
  },
  // Final batch to reach 250+
  {
    id: "extra_final_001",
    question: "¿Qué es 'spam'?",
    options: ["Mensajes no deseados masivos", "Una comida", "Un tipo de email válido", "Un virus"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Spam es el envío masivo de mensajes no solicitados, típicamente publicitarios.",
    tags: ["internet"],
  },
  {
    id: "extra_final_002",
    question: "¿Qué es un 'emoji'?",
    options: ["Icono gráfico en mensajes", "Una palabra japonesa", "Un tipo de letra", "Un sonido"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Los emojis son pequeños iconos digitales usados para expresar emociones o ideas.",
    tags: ["unicode"],
  },
  {
    id: "extra_final_003",
    question: "¿Qué es 'streaming'?",
    options: ["Transmitir contenido sin descargar", "Descargar archivos", "Grabar video", "Editar audio"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "Streaming reproduce contenido (video/audio) en tiempo real sin necesidad de descargarlo completo.",
    tags: ["media"],
  },
  {
    id: "extra_final_004",
    question: "¿Qué es 'zoom' en una cámara?",
    options: ["Acercamiento de imagen", "Un tipo de lente", "Flash de cámara", "Modo nocturno"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "El zoom permite acercar la imagen haciendo que el sujeto parezca más cercano.",
    tags: ["photography"],
  },
  {
    id: "extra_final_005",
    question: "¿Qué es 'download'?",
    options: ["Descargar archivos de internet", "Subir archivos", "Borrar archivos", "Copiar archivos"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Download (descargar) es transferir archivos desde un servidor remoto a tu dispositivo.",
    tags: ["internet"],
  },
];
