/**
 * Programming Category Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const programmingQuestions: TriviaQuestion[] = [
  // Difficulty 1
  {
    id: "prog_001",
    question: "¿Qué significa 'HTML'?",
    options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Main Link", "Home Tool Markup Language"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "HTML (HyperText Markup Language) es el lenguaje estándar para crear páginas web.",
    tags: ["web", "basics"],
  },
  {
    id: "prog_002",
    question: "¿Qué lenguaje se usa principalmente para estilos web?",
    options: ["Python", "JavaScript", "CSS", "SQL"],
    correctIndex: 2,
    category: "programming",
    difficulty: 1,
    explanation: "CSS (Cascading Style Sheets) controla el diseño y presentación visual de páginas web.",
    tags: ["web", "css"],
  },
  {
    id: "prog_003",
    question: "¿Cuál es el resultado de '2' + 2 en JavaScript?",
    options: ["4", "'22'", "NaN", "Error"],
    correctIndex: 1,
    category: "programming",
    difficulty: 1,
    explanation: "En JavaScript, '2' + 2 concatena como string, resultando en '22' (coerción de tipos).",
    tags: ["javascript", "types"],
  },
  {
    id: "prog_004",
    question: "¿Qué símbolo se usa para comentarios de una línea en JavaScript?",
    options: ["//", "/*", "#", "--"],
    correctIndex: 0,
    category: "programming",
    difficulty: 1,
    explanation: "// inicia un comentario de una línea en JavaScript, C++, Java y similares.",
    tags: ["javascript", "syntax"],
  },
  {
    id: "prog_005",
    question: "¿Qué es un 'array'?",
    options: ["Un tipo de variable", "Una estructura de datos ordenada", "Una función especial", "Un error común"],
    correctIndex: 1,
    category: "programming",
    difficulty: 1,
    explanation: "Un array es una estructura de datos que almacena elementos en orden indexado.",
    tags: ["data-structures", "basics"],
  },
  // Difficulty 2
  {
    id: "prog_006",
    question: "¿Qué significa 'API'?",
    options: ["Application Programming Interface", "Advanced Program Integration", "Automated Process Instruction", "Application Process Interface"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "API (Application Programming Interface) define cómo interactuar con un sistema o biblioteca.",
    tags: ["concepts", "api"],
  },
  {
    id: "prog_007",
    question: "¿Qué es 'JSON'?",
    options: ["JavaScript Object Notation", "Java System Object Network", "Joint System Object Notation", "JavaScript Online Notation"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "JSON es un formato ligero de intercambio de datos basado en sintaxis de objetos JavaScript.",
    tags: ["data-format", "json"],
  },
  {
    id: "prog_008",
    question: "¿Qué es un 'loop' for?",
    options: ["Un error", "Una estructura de repetición", "Un tipo de función", "Una variable"],
    correctIndex: 1,
    category: "programming",
    difficulty: 2,
    explanation: "Un loop for repite código un número específico de veces mientras cumpla una condición.",
    tags: ["control-flow", "loops"],
  },
  {
    id: "prog_009",
    question: "¿Qué es 'Git'?",
    options: ["Un lenguaje de programación", "Un sistema de control de versiones", "Un editor de código", "Un framework"],
    correctIndex: 1,
    category: "programming",
    difficulty: 2,
    explanation: "Git es un sistema distribuido de control de versiones creado por Linus Torvalds.",
    tags: ["version-control", "git"],
  },
  {
    id: "prog_010",
    question: "¿Qué hace 'console.log()' en JavaScript?",
    options: ["Muestra un mensaje en consola", "Guarda un archivo", "Crea una variable", "Borra datos"],
    correctIndex: 0,
    category: "programming",
    difficulty: 2,
    explanation: "console.log() imprime mensajes en la consola del navegador o Node.js para debugging.",
    tags: ["javascript", "debugging"],
  },
  // Difficulty 3
  {
    id: "prog_011",
    question: "¿Qué es 'SQL'?",
    options: ["Structured Query Language", "Simple Question Language", "System Query Logic", "Standard Query Link"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "SQL es el lenguaje estándar para consultar y manipular bases de datos relacionales.",
    tags: ["databases", "sql"],
  },
  {
    id: "prog_012",
    question: "¿Qué es 'recursión'?",
    options: ["Un bucle infinito", "Una función que se llama a sí misma", "Un tipo de variable", "Un error de código"],
    correctIndex: 1,
    category: "programming",
    difficulty: 3,
    explanation: "La recursión ocurre cuando una función se invoca a sí misma hasta alcanzar un caso base.",
    tags: ["algorithms", "functions"],
  },
  {
    id: "prog_013",
    question: "¿Qué es 'async/await' en JavaScript?",
    options: ["Sintaxis para operaciones asíncronas", "Un tipo de variable", "Un framework", "Un método de array"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "async/await es azúcar sintáctico para manejar Promesas de forma más legible.",
    tags: ["javascript", "async"],
  },
  {
    id: "prog_014",
    question: "¿Qué es 'Docker'?",
    options: ["Un sistema operativo", "Una plataforma de contenedores", "Un lenguaje de programación", "Una base de datos"],
    correctIndex: 1,
    category: "programming",
    difficulty: 3,
    explanation: "Docker empaqueta aplicaciones en contenedores portables con todas sus dependencias.",
    tags: ["devops", "containers"],
  },
  {
    id: "prog_015",
    question: "¿Qué es 'REST'?",
    options: ["Representational State Transfer", "Remote Execution Service Tool", "Rapid Entry System Technology", "Resource State Transfer"],
    correctIndex: 0,
    category: "programming",
    difficulty: 3,
    explanation: "REST es un estilo arquitectónico para diseñar APIs usando métodos HTTP estándar.",
    tags: ["api", "web", "architecture"],
  },
  // Difficulty 4
  {
    id: "prog_016",
    question: "¿Qué es 'polimorfismo' en POO?",
    options: ["Múltiples formas de un objeto", "Herencia múltiple", "Encapsulación de datos", "Un tipo de variable"],
    correctIndex: 0,
    category: "programming",
    difficulty: 4,
    explanation: "Polimorfismo permite que objetos de diferentes clases respondan al mismo mensaje de distintas formas.",
    tags: ["oop", "concepts"],
  },
  {
    id: "prog_017",
    question: "¿Qué es 'closure' en JavaScript?",
    options: ["Una función con acceso a su ámbito léxico", "Un método de array", "Un tipo de bucle", "Una clase"],
    correctIndex: 0,
    category: "programming",
    difficulty: 4,
    explanation: "Un closure es una función que recuerda el ámbito donde fue creada incluso ejecutándose fuera de él.",
    tags: ["javascript", "advanced"],
  },
  {
    id: "prog_018",
    question: "¿Qué es 'Big O notation'?",
    options: ["Notación musical", "Clasificación de complejidad algorítmica", "Un tipo de variable", "Sistema de tipos"],
    correctIndex: 1,
    category: "programming",
    difficulty: 4,
    explanation: "Big O describe la complejidad temporal o espacial de un algoritmo según crece la entrada.",
    tags: ["algorithms", "complexity"],
  },
  {
    id: "prog_019",
    question: "¿Qué es 'event loop' en JavaScript?",
    options: ["Un ciclo de eventos de DOM", "El mecanismo de concurrencia de JS", "Un tipo de bucle", "Una librería"],
    correctIndex: 1,
    category: "programming",
    difficulty: 4,
    explanation: "El event loop permite a JavaScript (monohilo) manejar operaciones asíncronas no bloqueantes.",
    tags: ["javascript", "runtime"],
  },
  // Difficulty 5
  {
    id: "prog_020",
    question: "¿Qué es 'memoization'?",
    options: ["Cache de resultados de función", "Memoria de computadora", "Documentación de código", "Un tipo de variable"],
    correctIndex: 0,
    category: "programming",
    difficulty: 5,
    explanation: "Memoization es una técnica de optimización que cachea resultados de funciones costosas.",
    tags: ["optimization", "algorithms"],
  },
  {
    id: "prog_021",
    question: "¿Qué es 'tree shaking'?",
    options: ["Eliminación de código muerto", "Un algoritmo de árboles", "Un tipo de estructura de datos", "Un framework"],
    correctIndex: 0,
    category: "programming",
    difficulty: 5,
    explanation: "Tree shaking es la eliminación automática de código no utilizado durante el bundle.",
    tags: ["bundling", "optimization"],
  },
  {
    id: "prog_022",
    question: "¿Qué es 'idempotencia' en APIs?",
    options: ["Múltiples llamadas idénticas producen el mismo resultado", "Llamadas únicas", "Autenticación única", "Un tipo de cifrado"],
    correctIndex: 0,
    category: "programming",
    difficulty: 5,
    explanation: "Una operación idempotente puede llamarse múltiples veces sin efectos secundarios adicionales.",
    tags: ["api", "concepts"],
  },
  {
    id: "prog_023",
    question: "¿Qué es 'RAII' en C++?",
    options: ["Resource Acquisition Is Initialization", "Random Access Input Interface", "Resource Allocation In Instance", "Runtime Automatic Initialization"],
    correctIndex: 0,
    category: "programming",
    difficulty: 5,
    explanation: "RAII vincula el ciclo de vida de recursos (memoria, archivos) al de objetos en C++.",
    tags: ["cpp", "memory-management"],
  },
];
