/**
 * Music trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const musicQuestions: TriviaQuestion[] = [
  {
    id: "music-1",
    question: "What is the most streamed song on Spotify of all time (as of 2024)?",
    options: ["'Blinding Lights' by The Weeknd", "'Shape of You' by Ed Sheeran", "'Bohemian Rhapsody' by Queen", "'Dance Monkey' by Tones and I"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "'Blinding Lights' by The Weeknd surpassed 4 billion streams to become Spotify's most streamed song. It spent 57 weeks in the top 10 of the Billboard Hot 100 — a record.",
    tags: ["spotify", "records", "the-weeknd"],
  },
  {
    id: "music-2",
    question: "What does 'BPM' stand for in music?",
    options: ["Beats Per Minute", "Bass Per Measure", "Beat Pattern Meter", "Bars Per Movement"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "BPM = Beats Per Minute. It measures tempo. A resting heart rate is ~60-100 BPM. Most pop songs are 100-130 BPM. Death metal can hit 200+ BPM. Your heart cannot keep up.",
    tags: ["music-theory", "tempo", "basics"],
  },
  {
    id: "music-3",
    question: "Which band was Freddie Mercury the lead singer of?",
    options: ["Queen", "Led Zeppelin", "The Rolling Stones", "Aerosmith"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Freddie Mercury was the iconic lead vocalist of Queen. His vocal range spanned nearly four octaves. 'Bohemian Rhapsody' (1975) is considered one of the greatest songs ever recorded.",
    tags: ["queen", "freddie-mercury", "rock"],
  },
  {
    id: "music-4",
    question: "What is a 'key change' in music?",
    options: ["Shifting the tonal center of a song to a different pitch", "Changing the time signature", "Switching from major to minor", "Transposing a song to a different instrument"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "A key change (modulation) shifts the tonal center of a song. It's used for emotional impact — usually upward for a dramatic finale. Whitney Houston's 'I Will Always Love You' has a famous key change that ends careers at karaoke.",
    tags: ["music-theory", "key-change", "modulation"],
  },
  {
    id: "music-5",
    question: "What is the name of the world's best-selling music artist of all time?",
    options: ["The Beatles", "Michael Jackson", "Elvis Presley", "Madonna"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "The Beatles are the best-selling music artists of all time with estimated sales of 600 million+ units. They broke up in 1970 and are still releasing new music in 2023. Death is apparently optional for The Beatles.",
    tags: ["beatles", "records", "classic-rock"],
  },
  {
    id: "music-6",
    question: "What does it mean when a song is in a 'minor key'?",
    options: ["It generally sounds sad, dark, or tense", "It's played at a lower volume", "It uses fewer instruments", "It's written for younger audiences"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "Minor keys generally evoke sadness, tension, or darkness due to the flattened third note. Major keys sound happy and bright. This is a simplification — but it's why sad songs are usually in minor keys.",
    tags: ["music-theory", "minor-key", "emotion"],
  },
  {
    id: "music-7",
    question: "What is 'autotune'?",
    options: ["Software that corrects pitch in vocal recordings", "A type of guitar tuner", "A music genre", "A method of mixing tracks"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Auto-Tune is pitch correction software created by Andy Hildebrand in 1997. It was first used subtly to fix off-key notes, then T-Pain made it an effect. Now it's everywhere. Hildebrand also worked on oil drilling software.",
    tags: ["autotune", "production", "technology"],
  },
  {
    id: "music-8",
    question: "What is the name of the Italian musical term meaning 'gradually getting louder'?",
    options: ["Crescendo", "Decrescendo", "Fortissimo", "Accelerando"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "Crescendo means gradually getting louder. Decrescendo (or diminuendo) means gradually getting softer. Fortissimo (ff) means very loud. Most people use 'crescendo' to mean 'climax' which is technically wrong but widely accepted.",
    tags: ["music-theory", "dynamics", "italian-terms"],
  },
  {
    id: "music-9",
    question: "What is the name of the guitar technique where you tap the strings on the fretboard with your picking hand?",
    options: ["Tapping", "Hammer-on", "Sweep picking", "Legato"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "Tapping involves using the picking hand's fingers to tap notes on the fretboard. Eddie Van Halen popularized it with 'Eruption' (1978). It sounds impossible until you see someone do it slowly.",
    tags: ["guitar", "technique", "van-halen"],
  },
  {
    id: "music-10",
    question: "What is a 'sample' in music production?",
    options: ["A portion of a recorded sound used in a new track", "A short preview of a song", "A demo version of a track", "A free download of a song"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Sampling is taking a portion of an existing recording and using it in a new composition. Hip-hop built an entire genre on sampling. It's also the source of countless lawsuits — Vanilla Ice famously denied sampling Queen.",
    tags: ["sampling", "hip-hop", "production"],
  },
  {
    id: "music-11",
    question: "What is the name of the famous four-chord progression used in countless pop songs?",
    options: ["I–V–vi–IV", "I–IV–V–I", "ii–V–I", "I–vi–IV–V"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "The I–V–vi–IV progression (e.g., C–G–Am–F) is used in hundreds of pop songs. The Axis of Awesome famously mashed together 40+ songs using it. Once you hear it, you can't unhear it.",
    tags: ["music-theory", "chords", "pop"],
  },
  {
    id: "music-12",
    question: "What is 'vinyl' in the context of music?",
    options: ["A type of record made from PVC plastic used to play music", "A music streaming service", "A type of guitar finish", "A music production software"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Vinyl records are analog audio storage discs made from PVC. They were the dominant music format from the 1950s–80s. They've had a massive resurgence — vinyl outsold CDs for the first time since 1987 in 2020.",
    tags: ["vinyl", "records", "analog"],
  },
  {
    id: "music-13",
    question: "What is the name of the music genre that originated in Jamaica in the late 1960s?",
    options: ["Reggae", "Ska", "Dancehall", "Calypso"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "Reggae originated in Jamaica in the late 1960s, evolving from ska and rocksteady. Bob Marley is its most famous ambassador. The genre is characterized by its offbeat rhythm and often carries social/political messages.",
    tags: ["reggae", "jamaica", "bob-marley"],
  },
  {
    id: "music-14",
    question: "What does 'LP' stand for in music?",
    options: ["Long Play", "Large Print", "Loud Performance", "Licensed Product"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "LP = Long Play, a vinyl record format that plays at 33⅓ RPM and holds about 20-25 minutes per side. EP = Extended Play (shorter). SP = Single Play. The terminology stuck even in the digital age.",
    tags: ["vinyl", "formats", "terminology"],
  },
  {
    id: "music-15",
    question: "What is the name of the technique where a singer rapidly alternates between chest voice and head voice?",
    options: ["Yodeling", "Vibrato", "Falsetto", "Melisma"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "Yodeling is the rapid alternation between chest voice (low register) and head voice/falsetto (high register). It originated in the Swiss Alps as a communication method. It's also the basis of many country music ornaments.",
    tags: ["vocals", "technique", "yodeling"],
  },
  {
    id: "music-16",
    question: "What is 'MIDI'?",
    options: ["A protocol for communicating musical information between electronic instruments", "A type of music file format", "A music production software", "A type of synthesizer"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "MIDI (Musical Instrument Digital Interface) is a protocol that lets electronic instruments and computers communicate. It doesn't carry audio — it carries instructions (note on, note off, velocity). Created in 1983, still used everywhere.",
    tags: ["midi", "technology", "production"],
  },
  {
    id: "music-17",
    question: "What is the name of the musical symbol that looks like a backwards 'S' and indicates a note should be held?",
    options: ["Fermata", "Tie", "Slur", "Tenuto"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "A fermata (the 'bird's eye' symbol — a dot under a curved line) indicates a note should be held longer than its written value, at the performer's discretion. It's the musical equivalent of 'hold on a sec'.",
    tags: ["music-notation", "symbols", "theory"],
  },
  {
    id: "music-18",
    question: "What is the name of the genre that blends country and rock music?",
    options: ["Country rock", "Rockabilly", "Americana", "Southern rock"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "Country rock blends country music with rock. The Eagles are one of the most famous country rock bands. Rockabilly is an earlier blend of country and rock 'n' roll. Americana is a broader umbrella term.",
    tags: ["country-rock", "genres", "eagles"],
  },
  {
    id: "music-19",
    question: "What is a 'hook' in a song?",
    options: ["The most memorable, catchy part of a song (usually the chorus)", "The opening riff of a song", "The bridge section", "The instrumental break"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "A hook is the most memorable, catchy part of a song — usually the chorus or a repeated melodic phrase. It's what gets stuck in your head at 3am. Good hooks are worth millions of dollars.",
    tags: ["songwriting", "hook", "structure"],
  },
  {
    id: "music-20",
    question: "What is the name of the famous music venue in Nashville, Tennessee?",
    options: ["The Grand Ole Opry", "Carnegie Hall", "The Apollo Theater", "Madison Square Garden"],
    correctIndex: 0,
    category: "music",
    difficulty: 2,
    explanation: "The Grand Ole Opry is the world's longest-running live radio program (since 1925) and the home of country music. Being invited to join the Opry is one of country music's highest honors.",
    tags: ["country-music", "nashville", "venues"],
  },
  {
    id: "music-21",
    question: "What is 'pitch' in music?",
    options: ["How high or low a sound is", "How loud or soft a sound is", "How fast or slow a song is", "The quality or timbre of a sound"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "Pitch refers to how high or low a sound is, determined by its frequency (Hz). Higher frequency = higher pitch. A4 (concert A) is standardized at 440 Hz. Perfect pitch is the ability to identify any note by ear.",
    tags: ["music-theory", "pitch", "basics"],
  },
  {
    id: "music-22",
    question: "What is the name of the music genre characterized by synthesizers, drum machines, and electronic production?",
    options: ["Electronic Dance Music (EDM)", "Synthpop", "Techno", "All of the above are valid answers"],
    correctIndex: 3,
    category: "music",
    difficulty: 2,
    explanation: "EDM, synthpop, and techno all fit the description — they're all electronic genres. EDM is the broad umbrella term. Techno originated in Detroit in the 1980s. Synthpop is more melodic. Genre boundaries are fuzzy.",
    tags: ["edm", "electronic", "genres"],
  },
  {
    id: "music-23",
    question: "What is the name of the famous Italian opera house in Milan?",
    options: ["La Scala", "La Fenice", "The Colosseum", "Teatro San Carlo"],
    correctIndex: 0,
    category: "music",
    difficulty: 3,
    explanation: "La Scala (Teatro alla Scala) in Milan is one of the world's most famous opera houses, opened in 1778. Performing there is considered the pinnacle of an opera singer's career. The audience is notoriously harsh.",
    tags: ["opera", "italy", "venues"],
  },
  {
    id: "music-24",
    question: "What is the name of the technique where a guitarist bends a string to raise its pitch?",
    options: ["String bending", "Vibrato", "Hammer-on", "Slide"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "String bending involves pushing or pulling a guitar string sideways to raise its pitch. It's a fundamental blues and rock technique. B.B. King's bends were so expressive he named his guitar 'Lucille'.",
    tags: ["guitar", "technique", "blues"],
  },
  {
    id: "music-25",
    question: "What is the name of the famous four-member band from Liverpool that changed music forever?",
    options: ["The Beatles", "The Rolling Stones", "The Who", "Led Zeppelin"],
    correctIndex: 0,
    category: "music",
    difficulty: 1,
    explanation: "The Beatles (John, Paul, George, Ringo) from Liverpool revolutionized popular music in the 1960s. They appeared on The Ed Sullivan Show in 1964 to 73 million viewers. Beatlemania was a documented psychological phenomenon.",
    tags: ["beatles", "classic-rock", "liverpool"],
  },
];
