/**
 * Extra trivia questions — mixed categories, weird facts, and curveballs.
 */

import type { TriviaQuestion } from "./types";

export const extraQuestions: TriviaQuestion[] = [
  {
    id: "extra-1",
    question: "A group of crows is called a 'murder'. What is a group of cats called?",
    options: ["A clowder", "A pride", "A pack", "A murder (they're just as guilty)"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "A group of cats is called a clowder (or a glaring, or a pounce). A group of kittens is a kindle. English collective nouns were clearly invented by someone who was having a great time.",
    tags: ["animals", "collective-nouns", "cats"],
  },
  {
    id: "extra-2",
    question: "What is the only food that never spoils?",
    options: ["Honey", "Salt", "Sugar", "Vinegar"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Honey never spoils due to its low moisture content, acidic pH, and hydrogen peroxide content. Edible honey has been found in 3,000-year-old Egyptian tombs. It was still fine. Bees are incredible.",
    tags: ["food", "science", "honey"],
  },
  {
    id: "extra-3",
    question: "How many licks does it take to get to the center of a Tootsie Pop, according to science?",
    options: ["About 364 licks (University of New York study)", "100 licks", "1,000 licks", "Nobody knows — the owl always bites"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "A University of New York study found it takes about 364 licks. Other studies range from 144 to 970. The owl in the commercial bites at 3, which is cheating. Science has priorities.",
    tags: ["food", "science", "tootsie-pop"],
  },
  {
    id: "extra-4",
    question: "What is the name of the phobia of long words?",
    options: ["Hippopotomonstrosesquippedaliophobia", "Logophobia", "Verbophobia", "Lexicophobia"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Hippopotomonstrosesquippedaliophobia is the fear of long words. The person who named it was either a genius or a monster. It's 36 letters long. The irony is intentional.",
    tags: ["phobias", "vocabulary", "irony"],
  },
  {
    id: "extra-5",
    question: "What percentage of the human body is water?",
    options: ["About 60%", "About 80%", "About 40%", "About 99%"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "The human body is about 60% water on average. Babies are about 75% water. The brain is about 73% water. You are mostly water that learned to worry about things.",
    tags: ["biology", "human-body", "water"],
  },
  {
    id: "extra-6",
    question: "What is the name of the font that was banned from official EU documents?",
    options: ["Comic Sans", "Times New Roman", "Arial", "Papyrus"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Comic Sans was informally banned from EU official documents. It was designed by Vincent Connare in 1994 for Microsoft Bob. It's the most hated font in design circles and the most beloved font in elementary schools.",
    tags: ["design", "comic-sans", "fonts"],
  },
  {
    id: "extra-7",
    question: "What is the name of the mathematical constant approximately equal to 2.71828?",
    options: ["Euler's number (e)", "Pi (π)", "The Golden Ratio (φ)", "The Imaginary Unit (i)"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Euler's number (e ≈ 2.71828) is the base of natural logarithms. It appears in compound interest, population growth, and probability. Pi gets all the attention but e is equally important and equally irrational.",
    tags: ["math", "constants", "euler"],
  },
  {
    id: "extra-8",
    question: "What is the name of the effect where a song gets stuck in your head?",
    options: ["Earworm (Ohrwurm)", "Musical hallucination", "Auditory loop", "Sonic echo"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "An earworm (from German 'Ohrwurm') is an involuntary musical imagery — a song stuck in your head. About 98% of people experience them. Songs with simple, repetitive melodies are most likely to become earworms.",
    tags: ["music", "psychology", "earworm"],
  },
  {
    id: "extra-9",
    question: "What is the world's most popular sport by viewership?",
    options: ["Soccer (Football)", "Cricket", "Basketball", "Tennis"],
    correctIndex: 0,
    category: "general",
    difficulty: 1,
    explanation: "Soccer (football) has an estimated 3.5 billion fans worldwide. The FIFA World Cup final regularly draws over 1 billion viewers. Americans call it soccer; the rest of the world calls it football; nobody agrees.",
    tags: ["sports", "soccer", "world"],
  },
  {
    id: "extra-10",
    question: "What is the name of the logical fallacy where you assume something is true because it hasn't been proven false?",
    options: ["Appeal to ignorance (Argumentum ad ignorantiam)", "Straw man fallacy", "False dichotomy", "Ad hominem"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The appeal to ignorance argues that something must be true because it hasn't been disproven. 'You can't prove ghosts don't exist, therefore they do.' It's the foundation of many internet arguments.",
    tags: ["logic", "fallacies", "reasoning"],
  },
  {
    id: "extra-11",
    question: "What is the name of the Japanese concept of finding beauty in imperfection and impermanence?",
    options: ["Wabi-sabi", "Ikigai", "Mono no aware", "Kaizen"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Wabi-sabi is the Japanese aesthetic of finding beauty in imperfection, incompleteness, and impermanence. A cracked tea bowl repaired with gold (kintsugi) is a perfect example. It's the opposite of Instagram.",
    tags: ["japanese", "philosophy", "aesthetics"],
  },
  {
    id: "extra-12",
    question: "What is the name of the phenomenon where you can't remember a word but feel it's on the tip of your tongue?",
    options: ["Tip-of-the-tongue phenomenon (TOT)", "Lethologica", "Presque vu", "Jamais vu"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The tip-of-the-tongue (TOT) phenomenon is when you know a word but can't retrieve it. It happens more with proper nouns and increases with age. The word usually comes to you at 3am.",
    tags: ["psychology", "memory", "language"],
  },
  {
    id: "extra-13",
    question: "What is the name of the world's largest desert?",
    options: ["Antarctica", "The Sahara", "The Arabian Desert", "The Gobi Desert"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Antarctica is the world's largest desert at 14.2 million km². A desert is defined by low precipitation, not heat. The Sahara is the largest hot desert. This is the trivia question that makes people feel cheated.",
    tags: ["geography", "deserts", "antarctica"],
  },
  {
    id: "extra-14",
    question: "What is the name of the cognitive bias where you overvalue things you own?",
    options: ["The Endowment Effect", "The Sunk Cost Fallacy", "The IKEA Effect", "Loss Aversion"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Endowment Effect is the tendency to overvalue things simply because you own them. People demand more to give up an object than they'd pay to acquire it. It's why selling your stuff on eBay is emotionally painful.",
    tags: ["psychology", "cognitive-bias", "economics"],
  },
  {
    id: "extra-15",
    question: "What is the name of the world's most venomous animal?",
    options: ["The box jellyfish", "The inland taipan snake", "The blue-ringed octopus", "The cone snail"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "The box jellyfish is considered the world's most venomous animal — its venom can kill a human in minutes. The inland taipan has the most toxic venom per bite, but box jellyfish deliver more total venom. The ocean is terrifying.",
    tags: ["animals", "venom", "ocean"],
  },
  {
    id: "extra-16",
    question: "What is the name of the paradox where a ship has all its parts replaced — is it still the same ship?",
    options: ["The Ship of Theseus", "Zeno's Paradox", "The Sorites Paradox", "Russell's Paradox"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "The Ship of Theseus asks: if you replace every plank of a ship one by one, is it still the same ship? It's a classic identity paradox. It also applies to your body — most of your cells are replaced every 7-10 years.",
    tags: ["philosophy", "paradox", "identity"],
  },
  {
    id: "extra-17",
    question: "What is the name of the fear of missing out on a good pun?",
    options: ["There isn't one — but there should be", "Punophobia", "Wordophobia", "Jokophobia"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "There's no official name for the fear of missing a good pun. But the fear of puns themselves is called 'paronomasiaphobia'. The real fear is making a pun and getting no reaction. That's just pain.",
    tags: ["humor", "puns", "wordplay"],
  },
  {
    id: "extra-18",
    question: "What is the name of the phenomenon where you feel like you've lived through a moment before?",
    options: ["Déjà vu", "Jamais vu", "Presque vu", "Déjà rêvé"],
    correctIndex: 0,
    category: "general",
    difficulty: 1,
    explanation: "Déjà vu (French: 'already seen') is the feeling that you've experienced a current situation before. About 60-70% of people experience it. Neuroscientists believe it's a memory processing glitch. Or time loops. Probably the first one.",
    tags: ["psychology", "memory", "deja-vu"],
  },
  {
    id: "extra-19",
    question: "What is the name of the world's most translated book?",
    options: ["The Bible", "The Quran", "Don Quixote", "Harry Potter"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "The Bible is the most translated book in history, available in over 3,000 languages. The full Bible exists in about 700 languages. The New Testament alone has been translated into 1,500+ languages.",
    tags: ["books", "religion", "translation"],
  },
  {
    id: "extra-20",
    question: "What is the name of the effect where background noise helps you concentrate?",
    options: ["The Stochastic Resonance Effect", "White Noise Effect", "The Coffee Shop Effect", "Ambient Focus"],
    correctIndex: 2,
    category: "general",
    difficulty: 3,
    explanation: "The 'Coffee Shop Effect' (or ambient noise effect) describes how moderate background noise (~70 dB) can boost creative thinking. Complete silence can actually be too distracting. This is why people work in cafés.",
    tags: ["psychology", "productivity", "noise"],
  },
  {
    id: "extra-21",
    question: "What is the name of the logical principle that says the simplest explanation is usually correct?",
    options: ["Occam's Razor", "Hanlon's Razor", "Hitchens's Razor", "Newton's Flaming Laser Sword"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Occam's Razor: among competing hypotheses, the one with fewest assumptions should be selected. Named after William of Ockham (14th century). Hanlon's Razor: never attribute to malice what can be explained by stupidity.",
    tags: ["logic", "philosophy", "occams-razor"],
  },
  {
    id: "extra-22",
    question: "What is the name of the Japanese practice of repairing broken pottery with gold?",
    options: ["Kintsugi", "Wabi-sabi", "Ikebana", "Origami"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Kintsugi (金継ぎ, 'golden joinery') repairs broken pottery with gold lacquer, treating the breakage as part of the object's history rather than something to hide. The repaired piece becomes more beautiful and valuable.",
    tags: ["japanese", "art", "kintsugi"],
  },
  {
    id: "extra-23",
    question: "What is the name of the world's most expensive coffee, made from beans eaten by civets?",
    options: ["Kopi Luwak", "Blue Mountain", "Jamaican Blue", "Geisha Coffee"],
    correctIndex: 0,
    category: "general",
    difficulty: 3,
    explanation: "Kopi Luwak is made from coffee beans eaten and excreted by Asian palm civets. The digestion process supposedly improves flavor. It costs up to $700/kg. Someone had to be the first person to try this. Respect.",
    tags: ["food", "coffee", "weird-facts"],
  },
  {
    id: "extra-24",
    question: "What is the name of the cognitive bias where you seek information that confirms your existing beliefs?",
    options: ["Confirmation Bias", "Anchoring Bias", "Availability Heuristic", "The Backfire Effect"],
    correctIndex: 0,
    category: "general",
    difficulty: 2,
    explanation: "Confirmation bias is the tendency to search for, interpret, and recall information that confirms your preexisting beliefs. It's one of the most pervasive cognitive biases and the engine that powers most internet arguments.",
    tags: ["psychology", "cognitive-bias", "confirmation-bias"],
  },
  {
    id: "extra-25",
    question: "What is the name of the mathematical proof that there are different sizes of infinity?",
    options: ["Cantor's Diagonal Argument", "Gödel's Incompleteness Theorem", "Russell's Paradox", "Hilbert's Hotel"],
    correctIndex: 0,
    category: "science",
    difficulty: 4,
    explanation: "Georg Cantor's Diagonal Argument (1891) proved that the infinity of real numbers is strictly larger than the infinity of natural numbers. There are infinitely many sizes of infinity. This broke several mathematicians' brains, including Cantor's.",
    tags: ["math", "infinity", "cantor"],
  },
];
