/**
 * Tech Category Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const techQuestions: TriviaQuestion[] = [
  // Difficulty 1 - Easy
  {
    id: "tech_001",
    question: "¿Qué significa 'CPU'?",
    options: ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Core Processing Unit"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "CPU son las siglas de Central Processing Unit (Unidad Central de Procesamiento), el cerebro de la computadora.",
    tags: ["hardware", "basics"],
  },
  {
    id: "tech_002",
    question: "¿Qué es 'RAM'?",
    options: ["Random Access Memory", "Read And Memory", "Random Allocation Memory", "Rapid Access Module"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "RAM (Random Access Memory) es la memoria de acceso aleatorio que usa la computadora para datos temporales.",
    tags: ["hardware", "memory"],
  },
  {
    id: "tech_003",
    question: "¿Cuál es el sistema operativo más usado en el mundo?",
    options: ["macOS", "Linux", "Windows", "Android"],
    correctIndex: 2,
    category: "tech",
    difficulty: 1,
    explanation: "Windows es el sistema operativo de escritorio más usado globalmente, desarrollado por Microsoft.",
    tags: ["software", "os"],
  },
  {
    id: "tech_004",
    question: "¿Qué significa 'URL'?",
    options: ["Uniform Resource Locator", "Universal Resource Link", "User Reference Link", "Unified Resource Locator"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "URL (Uniform Resource Locator) es la dirección web que identifica un recurso en internet.",
    tags: ["web", "basics"],
  },
  {
    id: "tech_005",
    question: "¿Qué compañía creó el iPhone?",
    options: ["Samsung", "Apple", "Google", "Microsoft"],
    correctIndex: 1,
    category: "tech",
    difficulty: 1,
    explanation: "Apple Inc. creó el iPhone, lanzado por primera vez en 2007.",
    tags: ["mobile", "apple"],
  },
  {
    id: "tech_006",
    question: "¿Qué es un 'byte'?",
    options: ["8 bits", "16 bits", "4 bits", "32 bits"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "Un byte está compuesto por 8 bits, siendo la unidad básica de información en computación.",
    tags: ["basics", "storage"],
  },
  {
    id: "tech_007",
    question: "¿Qué navegador web desarrolla Google?",
    options: ["Firefox", "Safari", "Edge", "Chrome"],
    correctIndex: 3,
    category: "tech",
    difficulty: 1,
    explanation: "Google Chrome es el navegador web desarrollado por Google, lanzado en 2008.",
    tags: ["web", "google"],
  },
  {
    id: "tech_008",
    question: "¿Qué significa 'WiFi'?",
    options: ["Wireless Fidelity", "Wire Free Internet", "Wireless Finder", "Wide Fidelity"],
    correctIndex: 0,
    category: "tech",
    difficulty: 1,
    explanation: "WiFi es una marca comercial que significa Wireless Fidelity, tecnología de conexión inalámbrica.",
    tags: ["networking", "wireless"],
  },
  // Difficulty 2 - Medium-Easy
  {
    id: "tech_009",
    question: "¿Qué es un 'SSD'?",
    options: ["Solid State Drive", "Super Storage Disk", "System Storage Drive", "Solid Storage Device"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "SSD (Solid State Drive) es una unidad de almacenamiento sin partes móviles, más rápida que los discos duros tradicionales.",
    tags: ["hardware", "storage"],
  },
  {
    id: "tech_010",
    question: "¿Qué protocolo se usa para enviar emails?",
    options: ["HTTP", "FTP", "SMTP", "TCP"],
    correctIndex: 2,
    category: "tech",
    difficulty: 2,
    explanation: "SMTP (Simple Mail Transfer Protocol) es el protocolo estándar para enviar correos electrónicos.",
    tags: ["networking", "email"],
  },
  {
    id: "tech_011",
    question: "¿Qué significa 'GPU'?",
    options: ["General Processing Unit", "Graphics Processing Unit", "Global Processing Unit", "Game Processing Unit"],
    correctIndex: 1,
    category: "tech",
    difficulty: 2,
    explanation: "GPU (Graphics Processing Unit) procesa gráficos y se usa mucho en videojuegos y machine learning.",
    tags: ["hardware", "graphics"],
  },
  {
    id: "tech_012",
    question: "¿Qué es 'la nube' en tecnología?",
    options: ["Almacenamiento en servidores remotos", "Almacenamiento en USB", "Backup en CD", "Memoria RAM extendida"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "La nube (cloud) se refiere a servidores remotos accesibles por internet para almacenar y procesar datos.",
    tags: ["cloud", "storage"],
  },
  {
    id: "tech_013",
    question: "¿Qué significa 'HDMI'?",
    options: ["High Definition Multimedia Interface", "High Data Media Input", "Home Digital Media Interface", "High Definition Media Input"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "HDMI es una interfaz multimedia de alta definición para transmitir video y audio digital.",
    tags: ["hardware", "video"],
  },
  {
    id: "tech_014",
    question: "¿Qué es un 'firewall'?",
    options: ["Un antivirus", "Una barrera de seguridad de red", "Un tipo de router", "Un sistema operativo"],
    correctIndex: 1,
    category: "tech",
    difficulty: 2,
    explanation: "Un firewall es un sistema de seguridad que controla el tráfico de red entrante y saliente.",
    tags: ["security", "networking"],
  },
  {
    id: "tech_015",
    question: "¿Qué significa 'USB'?",
    options: ["Universal Serial Bus", "United System Board", "Universal System Bus", "Ultra Serial Board"],
    correctIndex: 0,
    category: "tech",
    difficulty: 2,
    explanation: "USB (Universal Serial Bus) es un estándar de conexión para periféricos y dispositivos.",
    tags: ["hardware", "connectivity"],
  },
  // Difficulty 3 - Medium
  {
    id: "tech_016",
    question: "¿Qué es 'Docker'?",
    options: ["Un sistema operativo", "Una plataforma de contenedores", "Un lenguaje de programación", "Un tipo de base de datos"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "Docker es una plataforma que permite crear, desplegar y ejecutar aplicaciones en contenedores.",
    tags: ["devops", "containers"],
  },
  {
    id: "tech_017",
    question: "¿Qué significa 'HTTP 404'?",
    options: ["Error de servidor", "Recurso no encontrado", "Acceso denegado", "Tiempo de espera agotado"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "HTTP 404 significa que el recurso solicitado no fue encontrado en el servidor.",
    tags: ["web", "http"],
  },
  {
    id: "tech_018",
    question: "¿Qué es 'SSH'?",
    options: ["Secure Shell", "Simple Server Host", "System Security Hub", "Secure Socket Handler"],
    correctIndex: 0,
    category: "tech",
    difficulty: 3,
    explanation: "SSH (Secure Shell) es un protocolo para acceder seguro a sistemas remotos mediante cifrado.",
    tags: ["security", "networking"],
  },
  {
    id: "tech_019",
    question: "¿Qué es 'Kubernetes'?",
    options: ["Una base de datos", "Un orquestador de contenedores", "Un lenguaje de programación", "Un sistema operativo"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "Kubernetes es un sistema de orquestación de contenedores para automatizar su despliegue y escalado.",
    tags: ["devops", "containers"],
  },
  {
    id: "tech_020",
    question: "¿Qué significa 'DNS'?",
    options: ["Digital Name System", "Domain Name System", "Data Network Service", "Domain Network Server"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "DNS (Domain Name System) traduce nombres de dominio legibles a direcciones IP numéricas.",
    tags: ["networking", "web"],
  },
  {
    id: "tech_021",
    question: "¿Qué es un 'ping'?",
    options: ["Un virus", "Una herramienta de diagnóstico de red", "Un tipo de firewall", "Un protocolo de email"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "Ping es una herramienta que testea la conectividad entre dispositivos enviando paquetes de prueba.",
    tags: ["networking", "diagnostics"],
  },
  {
    id: "tech_022",
    question: "¿Qué es 'RAID' en almacenamiento?",
    options: ["Un tipo de disco duro", "Una tecnología de redundancia de discos", "Un sistema de backup", "Un antivirus"],
    correctIndex: 1,
    category: "tech",
    difficulty: 3,
    explanation: "RAID (Redundant Array of Independent Disks) combina múltiples discos para redundancia o rendimiento.",
    tags: ["hardware", "storage"],
  },
  // Difficulty 4 - Hard
  {
    id: "tech_023",
    question: "¿Qué es 'QoS' en redes?",
    options: ["Quality of Service", "Quick Operation System", "Query Optimization Service", "Queue Operating Standard"],
    correctIndex: 0,
    category: "tech",
    difficulty: 4,
    explanation: "QoS (Quality of Service) gestiona prioridades de tráfico de red para garantizar rendimiento crítico.",
    tags: ["networking", "performance"],
  },
  {
    id: "tech_024",
    question: "¿Qué es el 'efecto Rowhammer'?",
    options: ["Un ataque de hardware a RAM", "Un bug de software", "Un tipo de virus", "Un error de red"],
    correctIndex: 0,
    category: "tech",
    difficulty: 4,
    explanation: "Rowhammer es un ataque de hardware que explota la densidad de chips de memoria RAM para modificar datos.",
    tags: ["security", "hardware"],
  },
  {
    id: "tech_025",
    question: "¿Qué significa 'CAP theorem'?",
    options: ["Consistency, Availability, Partition tolerance", "Computer Architecture Protocol", "Cloud Application Platform", "Cryptographic Access Point"],
    correctIndex: 0,
    category: "tech",
    difficulty: 4,
    explanation: "El teorema CAP establece que en sistemas distribuidos solo se pueden garantizar 2 de 3: Consistencia, Disponibilidad o Tolerancia a particiones.",
    tags: ["distributed-systems", "theory"],
  },
  {
    id: "tech_026",
    question: "¿Qué es 'Meltdown'?",
    options: ["Un ataque de hardware a CPUs Intel", "Un tipo de malware", "Un error de software", "Un protocolo de red"],
    correctIndex: 0,
    category: "tech",
    difficulty: 4,
    explanation: "Meltdown es una vulnerabilidad de hardware que permite leer memoria del kernel en procesadores Intel.",
    tags: ["security", "hardware"],
  },
  {
    id: "tech_027",
    question: "¿Qué es 'BGP' en redes?",
    options: ["Border Gateway Protocol", "Basic Gateway Process", "Broadband Global Protocol", "Binary Gateway Path"],
    correctIndex: 0,
    category: "tech",
    difficulty: 4,
    explanation: "BGP (Border Gateway Protocol) es el protocolo de enrutamiento entre sistemas autónomos en internet.",
    tags: ["networking", "routing"],
  },
  // Difficulty 5 - Expert
  {
    id: "tech_028",
    question: "¿Qué es 'speculative execution' en CPUs?",
    options: ["Ejecución optimista de instrucciones", "Ejecución paralela de hilos", "Ejecución asíncrona", "Ejecución virtualizada"],
    correctIndex: 0,
    category: "tech",
    difficulty: 5,
    explanation: "La ejecución especulativa es una optimización donde la CPU ejecuta instrucciones antes de saber si se necesitan.",
    tags: ["hardware", "cpu", "optimization"],
  },
  {
    id: "tech_029",
    question: "¿Qué es 'RISC-V'?",
    options: ["Una arquitectura de conjunto de instrucciones abierta", "Un procesador Intel", "Un sistema operativo", "Un lenguaje de programación"],
    correctIndex: 0,
    category: "tech",
    difficulty: 5,
    explanation: "RISC-V es una arquitectura de conjunto de instrucciones (ISA) abierta y libre de regalías.",
    tags: ["hardware", "architecture"],
  },
  {
    id: "tech_030",
    question: "¿Qué es 'cache coherency'?",
    options: ["Consistencia de datos entre cachés multinúcleo", "Limpieza de caché del navegador", "Velocidad de caché", "Tamaño de caché"],
    correctIndex: 0,
    category: "tech",
    difficulty: 5,
    explanation: "Cache coherency garantiza que múltiples cachés de CPU vean los mismos valores para ubicaciones de memoria compartidas.",
    tags: ["hardware", "cpu", "memory"],
  },
];
