/**
 * Memes/Internet Culture Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const memeQuestions: TriviaQuestion[] = [
  // Difficulty 1
  {
    id: "meme_001",
    question: "¿Qué animal es el 'Doge' meme?",
    options: ["Gato", "Perro Shiba Inu", "Zorro", "Lobo"],
    correctIndex: 1,
    category: "memes",
    difficulty: 1,
    explanation: "Doge es un Shiba Inu japonés que se volvió viral en 2013 con texto en Comic Sans.",
    tags: ["doge", "classic"],
  },
  {
    id: "meme_002",
    question: "¿Qué significa 'LOL'?",
    options: ["Lots Of Love", "Laugh Out Loud", "Look Over There", "Little Old Lady"],
    correctIndex: 1,
    category: "memes",
    difficulty: 1,
    explanation: "LOL (Laugh Out Loud) significa reír en voz alta, uno de los acrónimos más antiguos de internet.",
    tags: ["slang", "texting"],
  },
  {
    id: "meme_003",
    question: "¿Qué es un 'troll' en internet?",
    options: ["Persona que provoca intencionalmente", "Un monstruo", "Un administrador", "Un robot"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "Un troll publica contenido controvertido para provocar reacciones negativas de otros.",
    tags: ["culture", "behavior"],
  },
  {
    id: "meme_004",
    question: "¿Qué significa 'BRB'?",
    options: ["Be Right Back", "Big Red Button", "Bring Random Bacon", "Best Response Best"],
    correctIndex: 0,
    category: "memes",
    difficulty: 1,
    explanation: "BRB (Be Right Back) indica que alguien regresará pronto a la conversación.",
    tags: ["slang", "texting"],
  },
  // Difficulty 2
  {
    id: "meme_005",
    question: "¿Qué es 'Rickrolling'?",
    options: ["Engañar con el video de Rick Astley", "Un baile", "Un juego", "Un tipo de spam"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Rickrolling es engañar a alguien para que vea 'Never Gonna Give You Up' de Rick Astley.",
    tags: ["prank", "classic"],
  },
  {
    id: "meme_006",
    question: "¿Qué es 'Pepe the Frog'?",
    options: ["Un personaje de comic que se volvió meme", "Un juego", "Una app", "Un emoji oficial"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "Pepe fue creado por Matt Furie en 2005 en 'Boy's Club' y se volvió un meme universal.",
    tags: ["character", "comic"],
  },
  {
    id: "meme_007",
    question: "¿Qué significa 'TL;DR'?",
    options: ["Too Long; Didn't Read", "Talk Later; Don't Reply", "The Last; Daily Report", "This Looks; Really Dumb"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "TL;DR resume texto largo. También se usa sarcásticamente ante publicaciones extensas.",
    tags: ["slang", "abbreviation"],
  },
  {
    id: "meme_008",
    question: "¿Qué es 'yeet'?",
    options: ["Lanzar algo con fuerza/entusiasmo", "Comer rápido", "Dormir", "Bailar"],
    correctIndex: 0,
    category: "memes",
    difficulty: 2,
    explanation: "'Yeet' significa lanzar con fuerza o expresar entusiasmo; originado en un video de Vine (2014).",
    tags: ["slang", "verb"],
  },
  // Difficulty 3
  {
    id: "meme_009",
    question: "¿De dónde viene 'This is fine' meme?",
    options: ["Un cómic de KC Green", "Una película", "Un anime", "Un comercial"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "'On Fire' (2013) de KC Green muestra un perro en una habitación en llamas diciendo 'esto está bien'.",
    tags: ["comic", "reaction"],
  },
  {
    id: "meme_010",
    question: "¿Qué es 'Loss' (la viñeta de Ctrl+Alt+Del)?",
    options: ["Un meme minimalista sobre miscarriage", "Un juego", "Una película", "Una canción"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "'Loss' (2008) de Tim Buckley se volvió meme por su representación minimalista: | || || |_",
    tags: ["comic", "abstract"],
  },
  {
    id: "meme_011",
    question: "¿Qué es 'sus' en Among Us?",
    options: ["Sospechoso/suspicious", "Super", "Success", "Susto"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "'Sus' es slang de 'suspicious' popularizado por Among Us en 2020 para describir comportamiento dudoso.",
    tags: ["gaming", "slang"],
  },
  {
    id: "meme_012",
    question: "¿Qué es 'copium'?",
    options: ["Ficción para afrontar decepciones", "Una droga", "Un juego", "Una app"],
    correctIndex: 0,
    category: "memes",
    difficulty: 3,
    explanation: "'Copium' es portmanteau de 'cope' (afrontar) y 'opium' (droga ficticia para negar la realidad).",
    tags: ["twitch", "slang"],
  },
  // Difficulty 4
  {
    id: "meme_013",
    question: "¿Qué es 'rule 34' de internet?",
    options: ["Si existe, hay porno de ello", "No hables de /b/", "Todo es un meme", "No hay girls on internet"],
    correctIndex: 0,
    category: "memes",
    difficulty: 4,
    explanation: "La Regla 34 de Internet dice: 'Si existe, hay pornografía de ello. Sin excepciones.'",
    tags: ["rules", "culture"],
  },
  {
    id: "meme_014",
    question: "¿Qué es 'based'?",
    options: ["Ser tú mismo sin importar opinión", "Basado en hechos", "Aburrido", "Antiguo"],
    correctIndex: 0,
    category: "memes",
    difficulty: 4,
    explanation: "'Based' significa tener opiniones propias sin preocuparse por la aceptación social.",
    tags: ["slang", "culture"],
  },
  {
    id: "meme_015",
    question: "¿De dónde viene 'Distracted Boyfriend' meme?",
    options: ["Una foto de stock española", "Una película", "Una serie", "Un comercial"],
    correctIndex: 0,
    category: "memes",
    difficulty: 4,
    explanation: "La foto fue tomada en 2015 por Antonio Guillem en España, mostrando infidelidad.",
    tags: ["stock-photo", "reaction"],
  },
  // Difficulty 5
  {
    id: "meme_016",
    question: "¿Qué es 'weird Twitter'?",
    options: ["Subcultura de humor absurdo surrealista", "Cuentas de bots", "Noticias raras", "Tweets borrados"],
    correctIndex: 0,
    category: "memes",
    difficulty: 5,
    explanation: "'Weird Twitter' fue una comunidad de humor anti-comedy, surrealista y experimental (2010-2015).",
    tags: ["culture", "history"],
  },
  {
    id: "meme_017",
    question: "¿Qué es 'copypasta'?",
    options: ["Texto copiado y pegado repetidamente", "Un tipo de comida", "Un virus", "Una app"],
    correctIndex: 0,
    category: "memes",
    difficulty: 5,
    explanation: "Copypasta es texto viral que se copia y pega masivamente, a menudo con variaciones.",
    tags: ["text", "culture"],
  },
  {
    id: "meme_018",
    question: "¿Qué significa 'touch grass'?",
    options: ["Sal afuera/deja internet", "Juega fútbol", "Toca plantas", "Haz ejercicio"],
    correctIndex: 0,
    category: "memes",
    difficulty: 5,
    explanation: "'Touch grass' se dice a alguien demasiado metido en internet para que reconecte con la realidad.",
    tags: ["slang", "insult"],
  },
];
