/**
 * Science Category Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const scienceQuestions: TriviaQuestion[] = [
  // Difficulty 1
  {
    id: "science_001",
    question: "¿Cuál es la fórmula química del agua?",
    options: ["CO2", "H2O", "O2", "NaCl"],
    correctIndex: 1,
    category: "science",
    difficulty: 1,
    explanation: "H2O indica que cada molécula de agua tiene 2 átomos de hidrógeno y 1 de oxígeno.",
    tags: ["chemistry"],
  },
  {
    id: "science_002",
    question: "¿A qué temperatura hierve el agua al nivel del mar?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    correctIndex: 1,
    category: "science",
    difficulty: 1,
    explanation: "El agua hierve a 100°C (212°F) a nivel del mar a presión atmosférica estándar.",
    tags: ["physics", "temperature"],
  },
  {
    id: "science_003",
    question: "¿Qué partícula tiene carga negativa?",
    options: ["Protón", "Neutrón", "Electrón", "Positrón"],
    correctIndex: 2,
    category: "science",
    difficulty: 1,
    explanation: "Los electrones tienen carga negativa, los protones positiva y los neutrones son neutros.",
    tags: ["physics", "atoms"],
  },
  {
    id: "science_004",
    question: "¿Cuántos planetas hay en el sistema solar?",
    options: ["7", "8", "9", "10"],
    correctIndex: 1,
    category: "science",
    difficulty: 1,
    explanation: "Hay 8 planetas desde que Plutón fue reclasificado como planeta enano en 2006.",
    tags: ["astronomy"],
  },
  {
    id: "science_005",
    question: "¿Qué órgano bombea sangre en el cuerpo humano?",
    options: ["Pulmones", "Cerebro", "Corazón", "Hígado"],
    correctIndex: 2,
    category: "science",
    difficulty: 1,
    explanation: "El corazón es un músculo que bombea sangre oxigenada por todo el cuerpo.",
    tags: ["biology", "anatomy"],
  },
  // Difficulty 2
  {
    id: "science_006",
    question: "¿Qué gas compone la mayor parte de la atmósfera terrestre?",
    options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"],
    correctIndex: 2,
    category: "science",
    difficulty: 2,
    explanation: "El nitrógeno (N2) constituye aproximadamente el 78% de la atmósfera.",
    tags: ["chemistry", "atmosphere"],
  },
  {
    id: "science_007",
    question: "¿Qué células transportan oxígeno en la sangre?",
    options: ["Glóbulos blancos", "Glóbulos rojos", "Plaquetas", "Linfocitos"],
    correctIndex: 1,
    category: "science",
    difficulty: 2,
    explanation: "Los glóbulos rojos contienen hemoglobina que transporta oxígeno desde los pulmones.",
    tags: ["biology"],
  },
  {
    id: "science_008",
    question: "¿Qué velocidad tiene la luz en el vacío?",
    options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "30,000 km/s"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "La luz viaja a 299,792 km/s (aproximadamente 300,000 km/s) en el vacío.",
    tags: ["physics", "light"],
  },
  {
    id: "science_009",
    question: "¿Qué proceso usan las plantas para obtener energía?",
    options: ["Respiración", "Fotosíntesis", "Fermentación", "Digestión"],
    correctIndex: 1,
    category: "science",
    difficulty: 2,
    explanation: "La fotosíntesis convierte luz solar, agua y CO2 en glucosa y oxígeno.",
    tags: ["biology", "botany"],
  },
  {
    id: "science_010",
    question: "¿Qué es el ADN?",
    options: ["Ácido desoxirribonucleico", "Ácido ribonucleico", "Proteína estructural", "Enzima digestiva"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "El ADN almacena la información genética de los seres vivos en su estructura de doble hélice.",
    tags: ["biology", "genetics"],
  },
  // Difficulty 3
  {
    id: "science_011",
    question: "¿Qué es la teoría de la relatividad?",
    options: ["E=mc² de Einstein", "Teoría de la evolución", "Teoría del Big Bang", "Teoría cuántica"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Einstein propuso que el espacio-tiempo se curva por la masa y la energía (E=mc²).",
    tags: ["physics", "einstein"],
  },
  {
    id: "science_012",
    question: "¿Qué es un quásar?",
    options: ["Una estrella cercana", "Un núcleo de galaxia activa muy luminoso", "Un planeta extrasolar", "Un agujero negro pequeño"],
    correctIndex: 1,
    category: "science",
    difficulty: 3,
    explanation: "Los quásares son galaxias distantes con núcleos superluminosos alimentados por agujeros negros supermasivos.",
    tags: ["astronomy"],
  },
  {
    id: "science_013",
    question: "¿Cuál es la unidad de resistencia eléctrica?",
    options: ["Voltio", "Amperio", "Ohmio", "Wattio"],
    correctIndex: 2,
    category: "science",
    difficulty: 3,
    explanation: "El ohmio (Ω) mide la resistencia eléctrica, nombrado en honor a Georg Ohm.",
    tags: ["physics", "electricity"],
  },
  {
    id: "science_014",
    question: "¿Qué es el mitocondrio?",
    options: ["Centro de energía celular", "Núcleo de la célula", "Pared celular", "Material genético"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Los mitocondrios producen ATP (energía) y tienen su propio ADN, probablemente de origen bacteriano.",
    tags: ["biology", "cells"],
  },
  {
    id: "science_015",
    question: "¿Qué es la antimateria?",
    options: ["Materia oscura", "Partículas opuestas a la materia normal", "Energía pura", "Vacío cuántico"],
    correctIndex: 1,
    category: "science",
    difficulty: 3,
    explanation: "La antimateria tiene partículas con carga opuesta; al contacto con materia se aniquilan liberando energía.",
    tags: ["physics", "particles"],
  },
  // Difficulty 4
  {
    id: "science_016",
    question: "¿Qué es el principio de incertidumbre de Heisenberg?",
    options: ["No se pueden conocer simultáneamente posición y momento exactos", "La materia no se crea ni destruye", "La energía se conserva", "La entropía siempre aumenta"],
    correctIndex: 0,
    category: "science",
    difficulty: 4,
    explanation: "Heisenberg estableció que en mecánica cuántica, mayor precisión en posición implica mayor incertidumbre en momento.",
    tags: ["physics", "quantum"],
  },
  {
    id: "science_017",
    question: "¿Qué es la entropía?",
    options: ["Medida de desorden en un sistema", "Energía cinética", "Masa en movimiento", "Fuerza gravitacional"],
    correctIndex: 0,
    category: "science",
    difficulty: 4,
    explanation: "La entropía mide el desorden molecular; la segunda ley de la termodinámica dice que siempre aumenta.",
    tags: ["physics", "thermodynamics"],
  },
  {
    id: "science_018",
    question: "¿Qué es la cromatina?",
    options: ["ADN empaquetado con proteínas", "Un tipo de célula", "Una proteína digestiva", "Una molécula de azúcar"],
    correctIndex: 0,
    category: "science",
    difficulty: 4,
    explanation: "La cromatina es ADN envuelto alrededor de histonas, que se condensa en cromosomas durante la división celular.",
    tags: ["biology", "genetics"],
  },
  // Difficulty 5
  {
    id: "science_019",
    question: "¿Qué es la radiación de Hawking?",
    options: ["Radiación emitida por agujeros negros", "Radiación cósmica de fondo", "Radiación gamma", "Radiación de fusión"],
    correctIndex: 0,
    category: "science",
    difficulty: 5,
    explanation: "Stephen Hawking predijo que los agujeros negros emiten radiación y eventualmente evaporan.",
    tags: ["physics", "black-holes"],
  },
  {
    id: "science_020",
    question: "¿Qué es el bosón de Higgs?",
    options: ["Partícula que da masa a otras partículas", "Partícula de luz", "Partícula de gravedad", "Partícula eléctrica"],
    correctIndex: 0,
    category: "science",
    difficulty: 5,
    explanation: "El bosón de Higgs y su campo explican cómo otras partículas adquieren masa (el 'campo de Dios').",
    tags: ["physics", "particles"],
  },
  {
    id: "science_021",
    question: "¿Qué es el problema de la medición en mecánica cuántica?",
    options: ["La observación altera el sistema medido", "Instrumentos imprecisos", "Errores de cálculo", "Efectos térmicos"],
    correctIndex: 0,
    category: "science",
    difficulty: 5,
    explanation: "En cuántica, medir un sistema colapsa su función de onda, cambiando su estado.",
    tags: ["physics", "quantum"],
  },
];
