/**
 * Science trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const scienceQuestions: TriviaQuestion[] = [
  {
    id: "science-1",
    question: "What is the only metal that is liquid at room temperature?",
    options: ["Mercury", "Gallium", "Cesium", "Francium"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Mercury is the only metal liquid at standard room temperature. Gallium melts just above room temperature (29.8°C), so it melts in your hand. Both are toxic. Don't eat either.",
    tags: ["chemistry", "metals", "elements"],
  },
  {
    id: "science-2",
    question: "What is the powerhouse of the cell?",
    options: ["The mitochondria", "The nucleus", "The ribosome", "The endoplasmic reticulum"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "The mitochondria is the powerhouse of the cell. This is the most memorized biology fact in history, thanks to every biology teacher ever. It produces ATP through cellular respiration.",
    tags: ["biology", "cells", "mitochondria"],
  },
  {
    id: "science-3",
    question: "What is Schrödinger's Cat thought experiment about?",
    options: ["A cat that is simultaneously alive and dead until observed", "A cat that can predict quantum events", "An experiment using cats to test radiation", "A paradox about whether cats have consciousness"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Schrödinger's Cat illustrates quantum superposition: a cat in a box with a quantum trigger is theoretically both alive and dead until observed. Schrödinger invented it to mock the Copenhagen interpretation. The cat is fine.",
    tags: ["quantum-physics", "schrodinger", "thought-experiments"],
  },
  {
    id: "science-4",
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "CaCl2", "MgSO4"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "Table salt is NaCl — sodium chloride. Sodium (Na) is a metal that explodes in water. Chlorine (Cl) is a toxic gas. Together they make the thing you put on your fries. Chemistry is wild.",
    tags: ["chemistry", "compounds", "everyday-science"],
  },
  {
    id: "science-5",
    question: "How many planets are in our solar system (as of 2006)?",
    options: ["8", "9", "10", "7"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "There are 8 planets since 2006, when Pluto was reclassified as a dwarf planet by the IAU. Pluto fans are still upset. The vote was 424 to 333, which is a surprisingly close call for planetary status.",
    tags: ["astronomy", "planets", "pluto"],
  },
  {
    id: "science-6",
    question: "What is the most abundant gas in Earth's atmosphere?",
    options: ["Nitrogen (78%)", "Oxygen (21%)", "Carbon dioxide", "Argon"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Nitrogen makes up about 78% of Earth's atmosphere. Oxygen is only 21%. We breathe mostly nitrogen, which is inert and does nothing for us. Oxygen is the important part.",
    tags: ["atmosphere", "chemistry", "earth"],
  },
  {
    id: "science-7",
    question: "What is the speed of sound in air (approximately)?",
    options: ["343 m/s", "1,000 m/s", "150 m/s", "3,000 m/s"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Sound travels at about 343 m/s in air at 20°C. That's why you see lightning before you hear thunder — light is ~880,000 times faster. Count seconds after lightning, divide by 3 for km distance.",
    tags: ["physics", "sound", "waves"],
  },
  {
    id: "science-8",
    question: "What is the half-life of Carbon-14?",
    options: ["About 5,730 years", "About 1,000 years", "About 50,000 years", "About 500 years"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Carbon-14 has a half-life of about 5,730 years. This is why radiocarbon dating works for organic material up to ~50,000 years old. After that, there's too little C-14 left to measure accurately.",
    tags: ["chemistry", "radioactivity", "dating"],
  },
  {
    id: "science-9",
    question: "What is the largest organ in the human body?",
    options: ["The skin", "The liver", "The brain", "The intestines"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "The skin is the largest organ, covering about 2 square meters and weighing 3-4 kg. If you said 'brain' you were thinking of most important, not largest. The skin is basically a wetsuit.",
    tags: ["biology", "human-body", "organs"],
  },
  {
    id: "science-10",
    question: "What is Newton's Third Law of Motion?",
    options: ["For every action, there is an equal and opposite reaction", "Force equals mass times acceleration", "An object in motion stays in motion", "Energy cannot be created or destroyed"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Newton's Third Law: for every action, there is an equal and opposite reaction. This is why rockets work in space, why you feel recoil when shooting, and why arguing on the internet never ends.",
    tags: ["physics", "newton", "laws-of-motion"],
  },
  {
    id: "science-11",
    question: "What is the pH of pure water?",
    options: ["7 (neutral)", "0 (acidic)", "14 (basic)", "It varies"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "Pure water has a pH of 7, which is neutral. Below 7 is acidic, above 7 is basic/alkaline. Battery acid is ~0, bleach is ~13. Your stomach acid is around 1.5-3.5. You're basically dissolving yourself.",
    tags: ["chemistry", "ph", "acids-bases"],
  },
  {
    id: "science-12",
    question: "What is the name of the force that keeps planets in orbit?",
    options: ["Gravity", "Electromagnetism", "The Strong Nuclear Force", "Centrifugal Force"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "Gravity keeps planets in orbit. Technically, planets are constantly 'falling' toward the Sun but moving sideways fast enough to keep missing it. Orbiting is just falling with style.",
    tags: ["physics", "gravity", "astronomy"],
  },
  {
    id: "science-13",
    question: "What is DNA an abbreviation for?",
    options: ["Deoxyribonucleic Acid", "Dynamic Nucleic Array", "Dual Nucleotide Assembly", "Deoxyribose Nucleotide Acid"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "DNA = Deoxyribonucleic Acid. It's the molecule that carries genetic instructions for all living organisms. If you printed out a human genome, it would fill about 200 phone books.",
    tags: ["biology", "genetics", "dna"],
  },
  {
    id: "science-14",
    question: "What is the Higgs Boson nicknamed?",
    options: ["The God Particle", "The God Boson", "The Universe Particle", "The Origin Particle"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "The Higgs Boson is nicknamed 'The God Particle' — a name physicist Leon Lederman wanted to call 'The Goddamn Particle' because it was so hard to find. Publishers made him change it. Confirmed in 2012 at CERN.",
    tags: ["particle-physics", "higgs-boson", "cern"],
  },
  {
    id: "science-15",
    question: "What is the most common blood type in humans?",
    options: ["O positive (O+)", "A positive (A+)", "B positive (B+)", "AB positive (AB+)"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "O positive (O+) is the most common blood type, found in about 38% of people. O negative (O-) is the universal donor. AB positive is the universal recipient. Blood types are complicated and important.",
    tags: ["biology", "blood-types", "medicine"],
  },
  {
    id: "science-16",
    question: "What is the name of the process by which plants make food?",
    options: ["Photosynthesis", "Respiration", "Osmosis", "Fermentation"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "Photosynthesis: plants use sunlight, water, and CO2 to produce glucose and oxygen. They're basically solar-powered sugar factories that also produce the air we breathe. Plants are underrated.",
    tags: ["biology", "plants", "photosynthesis"],
  },
  {
    id: "science-17",
    question: "What is the atomic number of gold?",
    options: ["79", "47", "82", "78"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Gold's atomic number is 79 (79 protons). Its symbol is Au from the Latin 'aurum'. It's one of the few elements that appears as a metal in nature. Alchemists spent centuries trying to make it. They failed.",
    tags: ["chemistry", "elements", "gold"],
  },
  {
    id: "science-18",
    question: "What is the theory that explains the origin of the universe?",
    options: ["The Big Bang Theory", "The Steady State Theory", "The Oscillating Universe Theory", "The Inflation Theory"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "The Big Bang Theory describes the universe expanding from an extremely hot, dense state ~13.8 billion years ago. It's also a TV show. The TV show is less scientifically accurate.",
    tags: ["cosmology", "big-bang", "universe"],
  },
  {
    id: "science-19",
    question: "What is the name of the boundary around a black hole beyond which nothing can escape?",
    options: ["Event Horizon", "Schwarzschild Radius", "Singularity", "Photon Sphere"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "The Event Horizon is the point of no return around a black hole — beyond it, not even light can escape. The Schwarzschild Radius defines its size. The singularity is the infinitely dense point at the center.",
    tags: ["astronomy", "black-holes", "physics"],
  },
  {
    id: "science-20",
    question: "What is the chemical symbol for iron?",
    options: ["Fe", "Ir", "In", "Io"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Iron's symbol is Fe, from the Latin 'ferrum'. Many element symbols come from Latin or Greek names: gold is Au (aurum), silver is Ag (argentum), lead is Pb (plumbum). Plumbers are named after lead. Concerning.",
    tags: ["chemistry", "elements", "symbols"],
  },
  {
    id: "science-21",
    question: "What is the name of the scientist who proposed the theory of evolution by natural selection?",
    options: ["Charles Darwin", "Gregor Mendel", "Alfred Russel Wallace", "Jean-Baptiste Lamarck"],
    correctIndex: 0,
    category: "science",
    difficulty: 1,
    explanation: "Charles Darwin proposed natural selection in 'On the Origin of Species' (1859). Alfred Russel Wallace independently developed the same theory, which prompted Darwin to finally publish after 20 years of procrastinating.",
    tags: ["biology", "evolution", "darwin"],
  },
  {
    id: "science-22",
    question: "What is absolute zero?",
    options: ["-273.15°C (0 Kelvin) — the lowest possible temperature", "0°C — the freezing point of water", "The temperature of outer space", "The temperature at which all chemical reactions stop"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Absolute zero is -273.15°C (0 Kelvin), the theoretical lowest temperature where all molecular motion stops. It's never been fully achieved — we've gotten within billionths of a degree, but never there.",
    tags: ["physics", "temperature", "thermodynamics"],
  },
  {
    id: "science-23",
    question: "What is the name of the process where a solid turns directly into a gas?",
    options: ["Sublimation", "Evaporation", "Condensation", "Deposition"],
    correctIndex: 0,
    category: "science",
    difficulty: 3,
    explanation: "Sublimation is when a solid turns directly into a gas without passing through liquid. Dry ice (solid CO2) sublimates at room temperature. It's also why ice cubes shrink in your freezer over time.",
    tags: ["chemistry", "phase-changes", "sublimation"],
  },
  {
    id: "science-24",
    question: "What is the name of the scientist who discovered penicillin?",
    options: ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Joseph Lister"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Alexander Fleming discovered penicillin in 1928 when he noticed mold killing bacteria in a petri dish he'd left out by accident. He went on holiday and came back to find the most important medical discovery of the 20th century.",
    tags: ["biology", "medicine", "penicillin"],
  },
  {
    id: "science-25",
    question: "What is the name of the force that causes objects to resist changes in their motion?",
    options: ["Inertia", "Friction", "Momentum", "Gravity"],
    correctIndex: 0,
    category: "science",
    difficulty: 2,
    explanation: "Inertia is the tendency of objects to resist changes in their state of motion. A body at rest stays at rest; a body in motion stays in motion — unless acted on by a force. It's also why you lurch forward when a car brakes.",
    tags: ["physics", "inertia", "newton"],
  },
];
