/**
 * Anime & manga trivia questions.
 */

import type { TriviaQuestion } from "./types";

export const animeQuestions: TriviaQuestion[] = [
  {
    id: "anime-1",
    question: "In Dragon Ball Z, how many episodes does it take Goku to charge a Spirit Bomb on Namek?",
    options: ["About 10 episodes", "1 episode", "About 3 episodes", "It happens instantly"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "The Namek Spirit Bomb saga is infamous for taking roughly 10 episodes while Namek was 'about to explode in 5 minutes'. DBZ's sense of time is a separate dimension entirely.",
    tags: ["dragon-ball-z", "goku", "humor"],
  },
  {
    id: "anime-2",
    question: "What is the name of the giant robot in Neon Genesis Evangelion that Shinji pilots?",
    options: ["Unit-01", "EVA-00", "Gundam", "Mechagodzilla"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Shinji pilots Evangelion Unit-01, a giant biomechanical mecha. The show is about giant robots fighting angels and also about Shinji's crippling anxiety. Mostly the anxiety.",
    tags: ["evangelion", "mecha", "shinji"],
  },
  {
    id: "anime-3",
    question: "In One Piece, what is the name of Luffy's signature attack?",
    options: ["Gum-Gum Pistol", "Rubber Rocket", "Stretch Strike", "Elastic Fist"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Luffy's signature move is the Gum-Gum Pistol — he stretches his arm back and launches a punch. It's simple, effective, and has been used approximately 10,000 times across the series.",
    tags: ["one-piece", "luffy", "attacks"],
  },
  {
    id: "anime-4",
    question: "What is the name of the notebook in Death Note that kills people?",
    options: ["Death Note", "The Grimoire", "The Book of Death", "Shinigami's Journal"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "It's called the Death Note. The show is named after it. Writing someone's name in it kills them. Light Yagami found one and immediately decided to become a god. Relatable.",
    tags: ["death-note", "light-yagami", "shinigami"],
  },
  {
    id: "anime-5",
    question: "What is the power system in Hunter x Hunter called?",
    options: ["Nen", "Chakra", "Haki", "Reiatsu"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Nen is the power system in HxH — users manipulate their life energy. It's one of the most complex and well-designed power systems in anime. The show is also perpetually on hiatus.",
    tags: ["hunter-x-hunter", "nen", "power-systems"],
  },
  {
    id: "anime-6",
    question: "In Fullmetal Alchemist: Brotherhood, what is the first rule of alchemy?",
    options: ["Equivalent Exchange", "No human transmutation", "Matter cannot be created", "All things are connected"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Equivalent Exchange: to gain something, you must sacrifice something of equal value. It's the central law of alchemy in FMA and also a solid life philosophy if you ignore the human transmutation part.",
    tags: ["fma", "alchemy", "equivalent-exchange"],
  },
  {
    id: "anime-7",
    question: "What is the name of the village Naruto is from?",
    options: ["Konohagakure (Hidden Leaf Village)", "Sunagakure (Hidden Sand)", "Kirigakure (Hidden Mist)", "Kumogakure (Hidden Cloud)"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Naruto is from Konohagakure, the Hidden Leaf Village. He dreams of becoming Hokage, the village leader. He achieves this, but only after approximately 700 episodes of flashbacks.",
    tags: ["naruto", "konoha", "villages"],
  },
  {
    id: "anime-8",
    question: "In Attack on Titan, what are the giant humanoid creatures called?",
    options: ["Titans", "Giants", "Colossi", "Shifters"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "They're called Titans. The show is called Attack on Titan. The naming committee was very straightforward. The lore behind them is considerably less straightforward.",
    tags: ["attack-on-titan", "titans", "aot"],
  },
  {
    id: "anime-9",
    question: "What is the name of the main character in Sword Art Online?",
    options: ["Kirito", "Asuna", "Klein", "Agil"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Kirito (Kazuto Kirigaya) is the protagonist of SAO. He's a solo player who somehow becomes the most powerful person in every game he plays. The term 'Kirito-kun' is now synonymous with overpowered protagonists.",
    tags: ["sao", "kirito", "isekai"],
  },
  {
    id: "anime-10",
    question: "What does 'isekai' mean as an anime genre?",
    options: ["A protagonist is transported to another world", "A story set in feudal Japan", "A slice-of-life school drama", "A supernatural mystery series"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Isekai (異世界) literally means 'different world'. The genre involves a protagonist being transported to a fantasy world, usually by dying. There are now more isekai anime than there are days in a year.",
    tags: ["isekai", "genre", "terminology"],
  },
  {
    id: "anime-11",
    question: "In My Hero Academia, what is Deku's real name?",
    options: ["Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "Tenya Iida"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Deku's real name is Izuku Midoriya. 'Deku' was originally an insult from Bakugo meaning 'useless', but Izuku reclaimed it as his hero name. Character development!",
    tags: ["mha", "deku", "midoriya"],
  },
  {
    id: "anime-12",
    question: "What is the name of the demon slayer organization in Demon Slayer?",
    options: ["Demon Slayer Corps", "The Hashira Order", "The Breathing Society", "Tanjiro's Army"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "The Demon Slayer Corps is the organization Tanjiro joins. Their elite members are called Hashira (Pillars). The naming convention is refreshingly literal.",
    tags: ["demon-slayer", "corps", "hashira"],
  },
  {
    id: "anime-13",
    question: "In Jujutsu Kaisen, what are the supernatural entities called?",
    options: ["Cursed Spirits", "Demons", "Yokai", "Hollows"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Cursed Spirits are born from negative human emotions. Jujutsu sorcerers fight them using Cursed Energy. The show has excellent animation and a habit of killing beloved characters.",
    tags: ["jjk", "cursed-spirits", "jujutsu"],
  },
  {
    id: "anime-14",
    question: "What is the name of the main character in Cowboy Bebop?",
    options: ["Spike Spiegel", "Jet Black", "Faye Valentine", "Edward Wong"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Spike Spiegel is the laid-back, jazz-loving bounty hunter protagonist of Cowboy Bebop. The show is widely considered one of the greatest anime ever made. 'See you, Space Cowboy...'",
    tags: ["cowboy-bebop", "spike", "classic"],
  },
  {
    id: "anime-15",
    question: "What is 'power of friendship' in anime?",
    options: ["When a character overcomes impossible odds through emotional bonds", "A specific power system", "A genre of anime", "When two characters fuse together"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "The 'power of friendship' is a beloved/mocked anime trope where a character wins through the strength of their emotional bonds rather than raw power. It's cheesy, it's everywhere, and it works every time.",
    tags: ["tropes", "power-of-friendship", "humor"],
  },
  {
    id: "anime-16",
    question: "In Bleach, what is the name of Ichigo's sword?",
    options: ["Zangetsu", "Senbonzakura", "Ryujin Jakka", "Benihime"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Ichigo's Zanpakuto is named Zangetsu (Slaying Moon). Its Bankai form is Tensa Zangetsu. Bleach has some of the most creative sword designs and names in anime.",
    tags: ["bleach", "ichigo", "zanpakuto"],
  },
  {
    id: "anime-17",
    question: "What is a 'tsundere'?",
    options: ["A character who is initially cold/hostile but gradually shows warmth", "A character who is always cheerful and energetic", "A character with a split personality", "A character who is shy and easily flustered"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Tsundere (from 'tsun tsun' = aloof and 'dere dere' = lovestruck) describes a character who is initially harsh or hostile but reveals a softer side over time. 'It's not like I like you or anything!'",
    tags: ["character-archetypes", "tsundere", "terminology"],
  },
  {
    id: "anime-18",
    question: "In Steins;Gate, what is the name of the time travel device?",
    options: ["Phone Microwave (Phone Wave)", "Time Leap Machine", "D-Mail", "SERN Device"],
    correctIndex: 0,
    category: "anime",
    difficulty: 3,
    explanation: "The Phone Microwave (Phone Wave) is a microwave that accidentally becomes a time machine by sending text messages to the past. It's one of the most creative sci-fi setups in anime.",
    tags: ["steins-gate", "time-travel", "okabe"],
  },
  {
    id: "anime-19",
    question: "What is the name of the main antagonist in Sailor Moon?",
    options: ["Queen Beryl", "Wiseman", "Galaxia", "Mistress 9"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Queen Beryl is the main villain of the first arc of Sailor Moon, serving the even greater evil Metallia. Sailor Moon has a new villain every season, each more dramatic than the last.",
    tags: ["sailor-moon", "queen-beryl", "magical-girl"],
  },
  {
    id: "anime-20",
    question: "What does 'nakama' mean in Japanese anime context?",
    options: ["Comrades/crewmates who are like family", "Enemy", "Teacher", "Rival"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Nakama means comrades or crewmates — people so close they're like family. In One Piece, Luffy's crew are his nakama. Speeches about nakama are a staple of shonen anime and will make you cry.",
    tags: ["one-piece", "nakama", "japanese"],
  },
  {
    id: "anime-21",
    question: "What is the name of the studio that made Spirited Away?",
    options: ["Studio Ghibli", "Toei Animation", "Madhouse", "Bones"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Studio Ghibli made Spirited Away (2001), directed by Hayao Miyazaki. It won the Academy Award for Best Animated Feature and is one of the highest-grossing films in Japanese history.",
    tags: ["studio-ghibli", "spirited-away", "miyazaki"],
  },
  {
    id: "anime-22",
    question: "In Code Geass, what is Lelouch's special power called?",
    options: ["Geass", "Sharingan", "Absolute Command", "Mind Control"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Lelouch's power is called Geass — specifically 'the Power of Absolute Obedience', allowing him to give one irresistible command to anyone he makes eye contact with. He uses it to start a revolution.",
    tags: ["code-geass", "lelouch", "geass"],
  },
  {
    id: "anime-23",
    question: "What is the name of the main character in No Game No Life?",
    options: ["Sora", "Shiro", "Jibril", "Stephanie"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Sora is the older sibling of the NEET gamer duo in No Game No Life. Together with his sister Shiro, they're known as 'Blank' — an undefeated online gaming legend who gets isekai'd into a world where everything is decided by games.",
    tags: ["no-game-no-life", "sora", "isekai"],
  },
  {
    id: "anime-24",
    question: "What is 'filler' in anime?",
    options: ["Episodes not based on the source manga, added to avoid catching up", "Low-budget animation episodes", "Recap episodes", "Side stories written by the author"],
    correctIndex: 0,
    category: "anime",
    difficulty: 1,
    explanation: "Filler episodes are anime-original content added when the anime catches up to the manga. Naruto is infamous for having ~40% filler. Watching filler is optional but skipping it requires a guide.",
    tags: ["filler", "anime-production", "naruto"],
  },
  {
    id: "anime-25",
    question: "In Mob Psycho 100, what is Mob's real name?",
    options: ["Shigeo Kageyama", "Reigen Arataka", "Ritsu Kageyama", "Teruki Hanazawa"],
    correctIndex: 0,
    category: "anime",
    difficulty: 2,
    explanation: "Mob's real name is Shigeo Kageyama. 'Mob' is a Japanese slang term for a background character — ironic since he's one of the most powerful espers alive. The show is about emotional growth, not just psychic battles.",
    tags: ["mob-psycho", "shigeo", "esper"],
  },
];
