/**
 * History Category Trivia Questions.
 */

import type { TriviaQuestion } from "./types";

export const historyQuestions: TriviaQuestion[] = [
  // Difficulty 1
  {
    id: "history_001",
    question: "¿En qué año descubrió América Cristóbal Colón?",
    options: ["1490", "1492", "1500", "1488"],
    correctIndex: 1,
    category: "history",
    difficulty: 1,
    explanation: "Colón llegó a América el 12 de octubre de 1492, creyendo que había llegado a la India.",
    tags: ["exploration", "america"],
  },
  {
    id: "history_002",
    question: "¿Quién fue el primer presidente de Estados Unidos?",
    options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"],
    correctIndex: 1,
    category: "history",
    difficulty: 1,
    explanation: "George Washington fue el primer presidente (1789-1797) y líder revolucionario.",
    tags: ["usa", "presidents"],
  },
  {
    id: "history_003",
    question: "¿Qué imperio construyó el Coliseo?",
    options: ["Griego", "Romano", "Egipcio", "Persa"],
    correctIndex: 1,
    category: "history",
    difficulty: 1,
    explanation: "El Coliseo romano se construyó entre 70-80 d.C. para espectáculos gladiatorios.",
    tags: ["rome", "architecture"],
  },
  {
    id: "history_004",
    question: "¿En qué año cayó el Muro de Berlín?",
    options: ["1987", "1989", "1991", "1985"],
    correctIndex: 1,
    category: "history",
    difficulty: 1,
    explanation: "El Muro de Berlín cayó el 9 de noviembre de 1989, símbolo del fin de la Guerra Fría.",
    tags: ["cold-war", "germany"],
  },
  // Difficulty 2
  {
    id: "history_005",
    question: "¿Quién pintó la Capilla Sixtina?",
    options: ["Leonardo da Vinci", "Miguel Ángel", "Rafael", "Donatello"],
    correctIndex: 1,
    category: "history",
    difficulty: 2,
    explanation: "Miguel Ángel pintó el techo de la Capilla Sixtina (1508-1512) incluyendo 'La creación de Adán'.",
    tags: ["art", "renaissance", "vatican"],
  },
  {
    id: "history_006",
    question: "¿Qué revolución comenzó en 1789?",
    options: ["Rusa", "Francesa", "Americana", "Industrial"],
    correctIndex: 1,
    category: "history",
    difficulty: 2,
    explanation: "La Revolución Francesa (1789-1799) derrocó la monarquía e inspiró ideales democráticos.",
    tags: ["revolution", "france"],
  },
  {
    id: "history_007",
    question: "¿Quién fue Cleopatra?",
    options: ["Reina de Grecia", "Última faraona de Egipto", "Emperatriz romana", "Reina de Persia"],
    correctIndex: 1,
    category: "history",
    difficulty: 2,
    explanation: "Cleopatra VII fue la última gobernante activa del Reino Ptolemaico de Egipto (69-30 a.C.).",
    tags: ["egypt", "antiquity"],
  },
  {
    id: "history_008",
    question: "¿Qué inició la Primera Guerra Mundial?",
    options: ["Invasión de Polonia", "Asesinato de Franz Ferdinand", "Hundimiento del Lusitania", "Revolución rusa"],
    correctIndex: 1,
    category: "history",
    difficulty: 2,
    explanation: "El asesinato del archiduque Franz Ferdinand en Sarajevo (1914) desencadenó la guerra.",
    tags: ["wwi", "war"],
  },
  // Difficulty 3
  {
    id: "history_009",
    question: "¿Qué fue el Renacimiento?",
    options: ["Período de florecimiento artístico e intelectual", "Una guerra", "Una peste", "Una invasión"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "El Renacimiento (siglos XIV-XVII) fue un renacer del arte, ciencia y cultura clásica en Europa.",
    tags: ["renaissance", "culture"],
  },
  {
    id: "history_010",
    question: "¿Quién escribió 'El Príncipe'?",
    options: ["Platón", "Maquiavelo", "Aristóteles", "Cicerón"],
    correctIndex: 1,
    category: "history",
    difficulty: 3,
    explanation: "Nicolás Maquiavelo escribió 'El Príncipe' (1513), tratado sobre poder político.",
    tags: ["literature", "politics", "italy"],
  },
  {
    id: "history_011",
    question: "¿Qué fue la Ruta de la Seda?",
    options: ["Ruta comercial entre Asia y Europa", "Ruta marítima a América", "Ruta de peregrinación", "Ruta militar"],
    correctIndex: 0,
    category: "history",
    difficulty: 3,
    explanation: "La Ruta de la Seda conectó China con el Mediterráneo por tierra, comerciando seda y especias.",
    tags: ["trade", "asia"],
  },
  {
    id: "history_012",
    question: "¿Quién fue Genghis Khan?",
    options: ["Emperador romano", "Fundador del Imperio Mongol", "Rey de Inglaterra", "Líder samurái"],
    correctIndex: 1,
    category: "history",
    difficulty: 3,
    explanation: "Genghis Khan (c. 1162-1227) unió las tribus mongolas creando el imperio terrestre más grande.",
    tags: ["mongolia", "empire"],
  },
  // Difficulty 4
  {
    id: "history_013",
    question: "¿Qué fue la Revolución Industrial?",
    options: ["Transición a manufactura mecanizada", "Revolución política", "Revolución agrícola", "Guerra civil"],
    correctIndex: 0,
    category: "history",
    difficulty: 4,
    explanation: "La Revolución Industrial (siglo XVIII-XIX) transformó sociedades agrarias en industriales.",
    tags: ["industrial", "economy"],
  },
  {
    id: "history_014",
    question: "¿Qué fue el Imperio Bizantino?",
    options: ["Continuación del Imperio Romano de Oriente", "Imperio en África", "Imperio americano", "Imperio asiático"],
    correctIndex: 0,
    category: "history",
    difficulty: 4,
    explanation: "El Imperio Bizantino (330-1453) fue la continuación griega del Imperio Romano con capital en Constantinopla.",
    tags: ["rome", "byzantine"],
  },
  {
    id: "history_015",
    question: "¿Quién fue Simón Bolívar?",
    options: ["Libertador de países sudamericanos", "Rey de España", "Presidente de México", "General argentino"],
    correctIndex: 0,
    category: "history",
    difficulty: 4,
    explanation: "Bolívar (1783-1830) liberó Venezuela, Colombia, Ecuador, Perú y Bolivia del imperio español.",
    tags: ["independence", "latin-america"],
  },
  // Difficulty 5
  {
    id: "history_016",
    question: "¿Qué fue el Concilio de Trento?",
    options: ["Reforma católica contra el protestantismo", "Reunión de reyes", "Tratado de paz", "Conquista militar"],
    correctIndex: 0,
    category: "history",
    difficulty: 5,
    explanation: "El Concilio de Trento (1545-1563) definió doctrinas católicas en respuesta a la Reforma Protestante.",
    tags: ["religion", "catholicism"],
  },
  {
    id: "history_017",
    question: "¿Qué fue la Guerra de los Treinta Años?",
    options: ["Conflicto religioso europeo", "Guerra entre Roma y Grecia", "Guerra civil inglesa", "Guerra franco-española"],
    correctIndex: 0,
    category: "history",
    difficulty: 5,
    explanation: "La Guerra de los Treinta Años (1618-1648) devastó Europa central por conflictos católicos vs protestantes.",
    tags: ["war", "religion"],
  },
  {
    id: "history_018",
    question: "¿Quién fue Aspasia de Mileto?",
    options: ["Filósofa y política ateniense", "Reina de Egipto", "Diosa griega", "Escritora romana"],
    correctIndex: 0,
    category: "history",
    difficulty: 5,
    explanation: "Aspasia (c. 470-400 a.C.) fue una influyente intelectual y compañera de Pericles en Atenas.",
    tags: ["greece", "philosophy", "women"],
  },
];
